In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_bids = pd.read_csv('bids.csv')

In [3]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

## Explore Data

In [4]:
df_train.info(max_cols=200)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2013 entries, 0 to 2012
Data columns (total 4 columns):
bidder_id          2013 non-null object
payment_account    2013 non-null object
address            2013 non-null object
outcome            2013 non-null float64
dtypes: float64(1), object(3)
memory usage: 63.0+ KB

In [5]:
df_bids.info(max_cols=200)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7656334 entries, 0 to 7656333
Data columns (total 9 columns):
bid_id         int64
bidder_id      object
auction        object
merchandise    object
device         object
time           int64
country        object
ip             object
url            object
dtypes: int64(2), object(7)
memory usage: 525.7+ MB

In [6]:
df_test.info(max_cols=200)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4700 entries, 0 to 4699
Data columns (total 3 columns):
bidder_id          4700 non-null object
payment_account    4700 non-null object
address            4700 non-null object
dtypes: object(3)
memory usage: 110.2+ KB

In [7]:
df_train.head(3)

,bidder_id,payment_account,address,outcome
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0
1,624f258b49e77713fc34034560f93fb3hu3jo,a3d2de7675556553a5f08e4c88d2c228v1sga,ae87054e5a97a8f840a3991d12611fdcrfbq3,0.0
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,a3d2de7675556553a5f08e4c88d2c2280cybl,92520288b50f03907041887884ba49c0cl0pd,0.0

In [8]:
df_bids.head(3)

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c
2,2,aa5f360084278b35d746fa6af3a7a1a5ra3xe,wa00e,home goods,phone2,9759243157894736,py,112.54.208.157,vasstdc27m7nks3

In [9]:
df_test.head(3)

,bidder_id,payment_account,address
0,49bb5a3c944b8fc337981cc7a9ccae41u31d7,a3d2de7675556553a5f08e4c88d2c228htx90,5d9fa1b71f992e7c7a106ce4b07a0a754le7c
1,a921612b85a1494456e74c09393ccb65ylp4y,a3d2de7675556553a5f08e4c88d2c228rs17i,a3d2de7675556553a5f08e4c88d2c228klidn
2,6b601e72a4d264dab9ace9d7b229b47479v6i,925381cce086b8cc9594eee1c77edf665zjpl,a3d2de7675556553a5f08e4c88d2c228aght0

In [10]:
for column in df_bids.columns:
    print(column + ': {}'.format(len(df_bids[column].unique())))

bid_id: 7656334
bidder_id: 6614
auction: 15051
merchandise: 10
device: 7351
time: 776529
country: 200
ip: 2303991
url: 1786351

In [11]:
for column in df_train.columns:
    print(column + ': {}'.format(len(df_train[column].unique())))

bidder_id: 2013
payment_account: 2013
address: 2013
outcome: 2

In [12]:
for column in df_test.columns:
    print(column + ': {}'.format(len(df_test[column].unique())))

bidder_id: 4700
payment_account: 4700
address: 4700

In [13]:
df_test.head()

,bidder_id,payment_account,address
0,49bb5a3c944b8fc337981cc7a9ccae41u31d7,a3d2de7675556553a5f08e4c88d2c228htx90,5d9fa1b71f992e7c7a106ce4b07a0a754le7c
1,a921612b85a1494456e74c09393ccb65ylp4y,a3d2de7675556553a5f08e4c88d2c228rs17i,a3d2de7675556553a5f08e4c88d2c228klidn
2,6b601e72a4d264dab9ace9d7b229b47479v6i,925381cce086b8cc9594eee1c77edf665zjpl,a3d2de7675556553a5f08e4c88d2c228aght0
3,eaf0ed0afc9689779417274b4791726cn5udi,a3d2de7675556553a5f08e4c88d2c228nclv5,b5714de1fd69d4a0d2e39d59e53fe9e15vwat
4,cdecd8d02ed8c6037e38042c7745f688mx5sf,a3d2de7675556553a5f08e4c88d2c228dtdkd,c3b363a3c3b838d58c85acf0fc9964cb4pnfa

## join tables to create dataset

In [14]:
df_joined_train = pd.merge(df_bids, df_train, on='bidder_id', how='inner')
df_joined_test = pd.merge(df_bids, df_test, on='bidder_id', how='inner')

## Explore Data

In [15]:
df_joined_train.info(max_cols=999)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3071224 entries, 0 to 3071223
Data columns (total 12 columns):
bid_id             int64
bidder_id          object
auction            object
merchandise        object
device             object
time               int64
country            object
ip                 object
url                object
payment_account    object
address            object
outcome            float64
dtypes: float64(1), int64(2), object(9)
memory usage: 304.6+ MB

In [16]:
df_joined_test.info(max_cols=999)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4585110 entries, 0 to 4585109
Data columns (total 11 columns):
bid_id             int64
bidder_id          object
auction            object
merchandise        object
device             object
time               int64
country            object
ip                 object
url                object
payment_account    object
address            object
dtypes: int64(2), object(9)
memory usage: 419.8+ MB

In [17]:
df_joined_train.head(3)

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url,payment_account,address,outcome
0,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c,a3d2de7675556553a5f08e4c88d2c228ucoac,42a3b61a1fe69d66ad60f3e347aa09b1erfe2,0.0
1,25,668d393e858e8126275433046bbd35c6tywop,38v0a,furniture,phone4,9759243315789473,bd,147.64.206.30,vasstdc27m7nks3,a3d2de7675556553a5f08e4c88d2c228ucoac,42a3b61a1fe69d66ad60f3e347aa09b1erfe2,0.0
2,39,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone35,9759243368421052,in,75.11.239.20,i92xwb95qdo901j,a3d2de7675556553a5f08e4c88d2c228ucoac,42a3b61a1fe69d66ad60f3e347aa09b1erfe2,0.0

In [18]:
df_joined_test.head(3)

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url,payment_account,address
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25
1,14,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,wberf,jewelry,phone15,9759243263157894,au,134.243.148.253,vasstdc27m7nks3,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25
2,106,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,hw5at,jewelry,phone80,9759243736842105,ke,227.231.81.211,v2gyrh0dbr31atn,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25

#### label is outcome

In [19]:
for column in df_joined_test.columns:
    print(column + ': {}'.format(len(df_joined_test[column].unique())))

bid_id: 4585110
bidder_id: 4630
auction: 13999
merchandise: 9
device: 6574
time: 768690
country: 197
ip: 1545217
url: 1174536
payment_account: 4630
address: 4630

## slice df by auction_id

In [20]:
# do this for both training and test

# auctions = df_joined_test['auction'].unique()
auctions = df_joined_train['auction'].unique()

auction_dictinoary = {}

print('auctions: {}'.format(len(auctions)))

counter = 1

for auction in auctions:
#     auction_dictinoary[auction] = df_joined_test.loc[df_joined_test['auction'] == auction].copy(deep=True)
    auction_dictinoary[auction] = df_joined_train.loc[df_joined_train['auction'] == auction].copy(deep=True)
    
    print('#{}, id: {}, df_shape: {}'.format(counter, auction, auction_dictinoary[auction].shape))
    counter = counter + 1

auctions: 12740
#1, id: aeqok, df_shape: (3949, 12)
#2, id: 38v0a, df_shape: (3471, 12)
#3, id: jkyzt, df_shape: (3872, 12)
#4, id: h2xrf, df_shape: (4709, 12)
#5, id: 19fz7, df_shape: (487, 12)
#6, id: ligr3, df_shape: (248, 12)
#7, id: jefix, df_shape: (41473, 12)
#8, id: bqmsa, df_shape: (154, 12)
#9, id: 55y7n, df_shape: (3174, 12)
#10, id: 7etdx, df_shape: (4433, 12)
#11, id: k1g7r, df_shape: (4239, 12)
#12, id: wsmh2, df_shape: (54, 12)
#13, id: bj2ts, df_shape: (1, 12)
#14, id: uo3lj, df_shape: (3409, 12)
#15, id: 7msk4, df_shape: (3689, 12)
#16, id: jowkm, df_shape: (46, 12)
#17, id: uuik1, df_shape: (4025, 12)
#18, id: 1rc8d, df_shape: (3036, 12)
#19, id: mt5kl, df_shape: (141, 12)
#20, id: skn87, df_shape: (13, 12)
#21, id: 3ii90, df_shape: (19, 12)
#22, id: iu9id, df_shape: (239, 12)
#23, id: sd48j, df_shape: (431, 12)
#24, id: lx703, df_shape: (985, 12)
#25, id: 6qiu5, df_shape: (35, 12)
#26, id: s2eob, df_shape: (594, 12)
#27, id: qc9yg, df_shape: (495, 12)
#28, id: 6mzx6, df_shape: (58, 12)
#29, id: wq579, df_shape: (515, 12)
#30, id: 4cpb1, df_shape: (9, 12)
#31, id: 0elom, df_shape: (2117, 12)
#32, id: a2q5w, df_shape: (1379, 12)
#33, id: 1m5t8, df_shape: (1076, 12)
#34, id: a3kxo, df_shape: (361, 12)
#35, id: k6b3h, df_shape: (24, 12)
#36, id: bbffn, df_shape: (719, 12)
#37, id: 9hp1k, df_shape: (331, 12)
#38, id: 7b4f3, df_shape: (8, 12)
#39, id: xs3pv, df_shape: (938, 12)
#40, id: y6g1q, df_shape: (1161, 12)
#41, id: ogjc4, df_shape: (1984, 12)
#42, id: gybn6, df_shape: (1923, 12)
#43, id: 6oj75, df_shape: (423, 12)
#44, id: 2a68d, df_shape: (23, 12)
#45, id: 4f04x, df_shape: (23, 12)
#46, id: g7xyg, df_shape: (1571, 12)
#47, id: kgmw8, df_shape: (332, 12)
#48, id: 9iq87, df_shape: (2316, 12)
#49, id: 3hgtx, df_shape: (1200, 12)
#50, id: 5c9dv, df_shape: (680, 12)
#51, id: 6fls8, df_shape: (194, 12)
#52, id: emh16, df_shape: (34, 12)
#53, id: xyh9f, df_shape: (90, 12)
#54, id: 82rui, df_shape: (4654, 12)
#55, id: yitr4, df_shape: (902, 12)
#56, id: ho70t, df_shape: (39, 12)
#57, id: zjteq, df_shape: (383, 12)
#58, id: ar1rn, df_shape: (242, 12)
#59, id: c8mny, df_shape: (1727, 12)
#60, id: haqkq, df_shape: (18, 12)
#61, id: 03n0o, df_shape: (10, 12)
#62, id: 16gks, df_shape: (1250, 12)
#63, id: y58n4, df_shape: (375, 12)
#64, id: 7ly5q, df_shape: (87, 12)
#65, id: 296xp, df_shape: (6332, 12)
#66, id: bjzi1, df_shape: (356, 12)
#67, id: 6q78q, df_shape: (8, 12)
#68, id: 699vb, df_shape: (1, 12)
#69, id: haao5, df_shape: (6, 12)
#70, id: zz4dz, df_shape: (42, 12)
#71, id: 2611x, df_shape: (1100, 12)
#72, id: jpxg4, df_shape: (156, 12)
#73, id: a80dg, df_shape: (560, 12)
#74, id: joan7, df_shape: (181, 12)
#75, id: a7l9p, df_shape: (217, 12)
#76, id: 8wapy, df_shape: (376, 12)
#77, id: p6dbe, df_shape: (142, 12)
#78, id: qy8gt, df_shape: (15, 12)
#79, id: 2bdoa, df_shape: (71, 12)
#80, id: ubf0h, df_shape: (56, 12)
#81, id: 3ddmc, df_shape: (7, 12)
#82, id: mdp2m, df_shape: (64, 12)
#83, id: nctlq, df_shape: (65, 12)
#84, id: sjcg0, df_shape: (109, 12)
#85, id: hhgmc, df_shape: (44, 12)
#86, id: 2jzsf, df_shape: (593, 12)
#87, id: asixj, df_shape: (138, 12)
#88, id: v37o7, df_shape: (25, 12)
#89, id: 46i7t, df_shape: (476, 12)
#90, id: x93p7, df_shape: (48, 12)
#91, id: 9qusi, df_shape: (147, 12)
#92, id: wsty2, df_shape: (353, 12)
#93, id: x88xo, df_shape: (11, 12)
#94, id: 9ivqb, df_shape: (1, 12)
#95, id: l8c92, df_shape: (705, 12)
#96, id: gbeaw, df_shape: (3, 12)
#97, id: ndjv7, df_shape: (42, 12)
#98, id: fffj3, df_shape: (26, 12)
#99, id: b6rrb, df_shape: (22, 12)
#100, id: 5bi3y, df_shape: (51, 12)
#101, id: 7fw08, df_shape: (55, 12)
#102, id: 2ba7b, df_shape: (23, 12)
#103, id: 0is93, df_shape: (35, 12)
#104, id: u9dyp, df_shape: (1055, 12)
#105, id: tb56z, df_shape: (24, 12)
#106, id: ksqse, df_shape: (171, 12)
#107, id: 9enup, df_shape: (169, 12)
#108, id: l2c7x, df_shape: (68, 12)
#109, id: 5lzzh, df_shape: (479, 12)
#110, id: dh25q, df_shape: (138, 12)
#111, id: wuzq6, df_shape: (34, 12)
#112, id: zfp7e, df_shape: (108, 12)
#113, id: btsjy, df_shape: (424, 12)
#114, id: mwpmu, df_shape: (11, 12)
#115, id: guojw, df_shape: (133, 12)
#116, id: 5mh41, df_shape: (68, 12)
#117, id: pfl78, df_shape: (379, 12)
#118, id: t118o, df_shape: (101, 12)
#119, id: x4bgz, df_shape: (151, 12)
#120, id: 5jmvx, df_shape: (111, 12)
#121, id: 3gklo, df_shape: (91, 12)
#122, id: 3kg7y, df_shape: (523, 12)
#123, id: eg7i4, df_shape: (1677, 12)
#124, id: 7toe4, df_shape: (10, 12)
#125, id: krvi4, df_shape: (118, 12)
#126, id: 7hkup, df_shape: (147, 12)
#127, id: 3f519, df_shape: (12, 12)
#128, id: ua1j5, df_shape: (9, 12)
#129, id: uxd0f, df_shape: (104, 12)
#130, id: adv46, df_shape: (26, 12)
#131, id: 1sate, df_shape: (159, 12)
#132, id: slwqk, df_shape: (497, 12)
#133, id: xfvqn, df_shape: (243, 12)
#134, id: grptz, df_shape: (396, 12)
#135, id: mywrs, df_shape: (24, 12)
#136, id: 598wk, df_shape: (29, 12)
#137, id: 73tu7, df_shape: (244, 12)
#138, id: 8hvgd, df_shape: (385, 12)
#139, id: 6y9rw, df_shape: (1612, 12)
#140, id: lswz2, df_shape: (12, 12)
#141, id: wfiyw, df_shape: (530, 12)
#142, id: m03gz, df_shape: (170, 12)
#143, id: hj26z, df_shape: (28, 12)
#144, id: 9p6sc, df_shape: (43, 12)
#145, id: qpslu, df_shape: (25, 12)
#146, id: skx7d, df_shape: (150, 12)
#147, id: vi4bm, df_shape: (973, 12)
#148, id: s3u3o, df_shape: (50, 12)
#149, id: vs8fu, df_shape: (805, 12)
#150, id: pc0ll, df_shape: (5, 12)
#151, id: etwp7, df_shape: (137, 12)
#152, id: ihyc7, df_shape: (7, 12)
#153, id: 2491g, df_shape: (1, 12)
#154, id: yqmyo, df_shape: (22, 12)
#155, id: yrb80, df_shape: (35, 12)
#156, id: 1wb4n, df_shape: (7, 12)
#157, id: uvo6j, df_shape: (79, 12)
#158, id: g1apd, df_shape: (163, 12)
#159, id: 0pvd4, df_shape: (2512, 12)
#160, id: hnt2q, df_shape: (6, 12)
#161, id: dir3u, df_shape: (13, 12)
#162, id: hzd4m, df_shape: (64, 12)
#163, id: xpevf, df_shape: (75, 12)
#164, id: oz20z, df_shape: (15, 12)
#165, id: 596oe, df_shape: (44, 12)
#166, id: ieb1l, df_shape: (40, 12)
#167, id: 0rfbz, df_shape: (108, 12)
#168, id: dm7xj, df_shape: (354, 12)
#169, id: 9ztt5, df_shape: (2, 12)
#170, id: hfklr, df_shape: (98, 12)
#171, id: ok8sl, df_shape: (59, 12)
#172, id: usqk4, df_shape: (7, 12)
#173, id: bpdr2, df_shape: (13, 12)
#174, id: psscd, df_shape: (23, 12)
#175, id: 7pe7y, df_shape: (4, 12)
#176, id: 9odoj, df_shape: (328, 12)
#177, id: zi89z, df_shape: (148, 12)
#178, id: v4xhq, df_shape: (19, 12)
#179, id: peu2g, df_shape: (184, 12)
#180, id: 1phco, df_shape: (10, 12)
#181, id: c2zqq, df_shape: (7, 12)
#182, id: smtig, df_shape: (57, 12)
#183, id: yybkv, df_shape: (9, 12)
#184, id: xs0cg, df_shape: (316, 12)
#185, id: 9kpyb, df_shape: (9, 12)
#186, id: gzc9j, df_shape: (95, 12)
#187, id: 6d5ei, df_shape: (18, 12)
#188, id: q1qxn, df_shape: (19, 12)
#189, id: kjj7y, df_shape: (195, 12)
#190, id: 6reix, df_shape: (12, 12)
#191, id: rqvzp, df_shape: (2, 12)
#192, id: tbo6v, df_shape: (406, 12)
#193, id: igudx, df_shape: (2, 12)
#194, id: njueu, df_shape: (5, 12)
#195, id: icnuk, df_shape: (34, 12)
#196, id: 09gee, df_shape: (134, 12)
#197, id: pdqvc, df_shape: (125, 12)
#198, id: 2px6h, df_shape: (75, 12)
#199, id: 0vdfa, df_shape: (6, 12)
#200, id: vlatj, df_shape: (133, 12)
#201, id: vrsb8, df_shape: (41, 12)
#202, id: fvxzh, df_shape: (2, 12)
#203, id: ywlx6, df_shape: (69, 12)
#204, id: n38g3, df_shape: (223, 12)
#205, id: m8oam, df_shape: (59, 12)
#206, id: c0uyt, df_shape: (297, 12)
#207, id: yfjur, df_shape: (83, 12)
#208, id: u5ham, df_shape: (88, 12)
#209, id: sc1cr, df_shape: (230, 12)
#210, id: aoz8w, df_shape: (210, 12)
#211, id: kp551, df_shape: (209, 12)
#212, id: 8tzhu, df_shape: (71, 12)
#213, id: bdhvh, df_shape: (56, 12)
#214, id: xvvrv, df_shape: (37, 12)
#215, id: q2mgb, df_shape: (5, 12)
#216, id: lj7r5, df_shape: (18, 12)
#217, id: f40o4, df_shape: (272, 12)
#218, id: bshqb, df_shape: (482, 12)
#219, id: e7uxe, df_shape: (59, 12)
#220, id: crsqr, df_shape: (84, 12)
#221, id: rhl2m, df_shape: (225, 12)
#222, id: mo1nr, df_shape: (829, 12)
#223, id: xsr8t, df_shape: (269, 12)
#224, id: evvst, df_shape: (25, 12)
#225, id: 54pf4, df_shape: (35, 12)
#226, id: iwmaj, df_shape: (18, 12)
#227, id: cexmb, df_shape: (111, 12)

#228, id: 0g84z, df_shape: (14, 12)
#229, id: gm1i4, df_shape: (26, 12)
#230, id: g8bq6, df_shape: (120, 12)
#231, id: p18bn, df_shape: (311, 12)
#232, id: j7xjk, df_shape: (375, 12)
#233, id: 55gr6, df_shape: (5, 12)
#234, id: n8xd2, df_shape: (1541, 12)
#235, id: 6z974, df_shape: (9, 12)
#236, id: nypqy, df_shape: (49, 12)
#237, id: zvu8f, df_shape: (84, 12)
#238, id: harwh, df_shape: (26, 12)
#239, id: kkhsk, df_shape: (9, 12)
#240, id: wey7l, df_shape: (2532, 12)
#241, id: wicy8, df_shape: (126, 12)
#242, id: cs5hz, df_shape: (383, 12)
#243, id: d165x, df_shape: (415, 12)
#244, id: 2amjg, df_shape: (53, 12)
#245, id: gptxv, df_shape: (2525, 12)
#246, id: dccvv, df_shape: (4, 12)
#247, id: pmn3l, df_shape: (19, 12)
#248, id: zwmrq, df_shape: (45, 12)
#249, id: 9cki2, df_shape: (146, 12)
#250, id: sz8v4, df_shape: (48, 12)
#251, id: fle9d, df_shape: (11, 12)
#252, id: hz6gv, df_shape: (412, 12)
#253, id: 0tkzn, df_shape: (380, 12)
#254, id: buglu, df_shape: (79, 12)
#255, id: zzal8, df_shape: (18, 12)
#256, id: vdzrn, df_shape: (32, 12)
#257, id: 48dnf, df_shape: (78, 12)
#258, id: ehzpa, df_shape: (72, 12)
#259, id: mov0z, df_shape: (1, 12)
#260, id: k5log, df_shape: (283, 12)
#261, id: aqfna, df_shape: (182, 12)
#262, id: zdkyz, df_shape: (2, 12)
#263, id: bheo4, df_shape: (2, 12)
#264, id: nm6v3, df_shape: (3, 12)
#265, id: mvz94, df_shape: (5, 12)
#266, id: hsbhs, df_shape: (1, 12)
#267, id: tp009, df_shape: (19, 12)
#268, id: kiwbl, df_shape: (14, 12)
#269, id: aba00, df_shape: (35, 12)
#270, id: u32z0, df_shape: (209, 12)
#271, id: wthc6, df_shape: (71, 12)
#272, id: 6q5qx, df_shape: (137, 12)
#273, id: zyrd9, df_shape: (402, 12)
#274, id: oggbw, df_shape: (253, 12)
#275, id: rq0j7, df_shape: (86, 12)
#276, id: 1l0kl, df_shape: (187, 12)
#277, id: 0de93, df_shape: (91, 12)
#278, id: pib86, df_shape: (19, 12)
#279, id: hsitf, df_shape: (374, 12)
#280, id: 7fugk, df_shape: (141, 12)
#281, id: wf2mp, df_shape: (31, 12)
#282, id: qt9mx, df_shape: (50, 12)
#283, id: 8w0ms, df_shape: (15, 12)
#284, id: jqonr, df_shape: (67, 12)
#285, id: bp0qp, df_shape: (25, 12)
#286, id: pj96u, df_shape: (1, 12)
#287, id: q272n, df_shape: (2, 12)
#288, id: pzihy, df_shape: (12, 12)
#289, id: r4ouf, df_shape: (23, 12)
#290, id: 6esyq, df_shape: (261, 12)
#291, id: j976a, df_shape: (14, 12)
#292, id: 71nze, df_shape: (283, 12)
#293, id: 61qzn, df_shape: (932, 12)
#294, id: rryl4, df_shape: (604, 12)
#295, id: pofgg, df_shape: (323, 12)
#296, id: zs1u4, df_shape: (732, 12)
#297, id: ielks, df_shape: (617, 12)
#298, id: yis12, df_shape: (801, 12)
#299, id: ub38r, df_shape: (103, 12)
#300, id: lehw3, df_shape: (4779, 12)
#301, id: 2chvc, df_shape: (65, 12)
#302, id: ut8yk, df_shape: (39, 12)
#303, id: pb9ng, df_shape: (801, 12)
#304, id: 6wbk0, df_shape: (353, 12)
#305, id: p7z3n, df_shape: (7, 12)
#306, id: xxcm6, df_shape: (5, 12)
#307, id: p65u0, df_shape: (66, 12)
#308, id: hdhwz, df_shape: (149, 12)
#309, id: dk9yf, df_shape: (1, 12)
#310, id: t0e81, df_shape: (702, 12)
#311, id: o62to, df_shape: (2, 12)
#312, id: 8o5xi, df_shape: (114, 12)
#313, id: kjqdg, df_shape: (7, 12)
#314, id: 5lhs6, df_shape: (14, 12)
#315, id: wxslb, df_shape: (31, 12)
#316, id: fm7tr, df_shape: (1, 12)
#317, id: s2l8l, df_shape: (4, 12)
#318, id: g35w8, df_shape: (10, 12)
#319, id: tiipz, df_shape: (14, 12)
#320, id: hx2l5, df_shape: (60, 12)
#321, id: c341p, df_shape: (18, 12)
#322, id: anxc5, df_shape: (34, 12)
#323, id: maoby, df_shape: (78, 12)
#324, id: altkd, df_shape: (50, 12)
#325, id: jl492, df_shape: (6, 12)
#326, id: dlv9o, df_shape: (107, 12)
#327, id: 4hjdv, df_shape: (5, 12)
#328, id: 9grtm, df_shape: (51, 12)
#329, id: 82nhy, df_shape: (101, 12)
#330, id: x8580, df_shape: (125, 12)
#331, id: b779a, df_shape: (410, 12)
#332, id: 4o3md, df_shape: (3, 12)
#333, id: tep1m, df_shape: (5763, 12)
#334, id: uexhz, df_shape: (3, 12)
#335, id: atsc4, df_shape: (83, 12)
#336, id: 6w2af, df_shape: (26, 12)
#337, id: 4j96x, df_shape: (8, 12)
#338, id: 4k33p, df_shape: (69, 12)
#339, id: wa146, df_shape: (54, 12)
#340, id: 9l6ps, df_shape: (195, 12)
#341, id: 4u1xz, df_shape: (57, 12)
#342, id: u0m8k, df_shape: (12, 12)
#343, id: zaadd, df_shape: (9, 12)
#344, id: cessk, df_shape: (8, 12)
#345, id: jbtv2, df_shape: (17, 12)
#346, id: xgg0i, df_shape: (27, 12)
#347, id: 2lgl4, df_shape: (43, 12)
#348, id: iw81c, df_shape: (43, 12)
#349, id: tl0dj, df_shape: (55, 12)
#350, id: s0cov, df_shape: (189, 12)
#351, id: n1686, df_shape: (3, 12)
#352, id: uq7h6, df_shape: (12, 12)
#353, id: 2iwdg, df_shape: (13, 12)
#354, id: xfpij, df_shape: (4, 12)
#355, id: 3ab6i, df_shape: (16, 12)
#356, id: guuu9, df_shape: (1, 12)
#357, id: zv5qo, df_shape: (33, 12)
#358, id: hn0kd, df_shape: (84, 12)
#359, id: 16pka, df_shape: (10, 12)
#360, id: xdxdq, df_shape: (24, 12)
#361, id: oi50o, df_shape: (29, 12)
#362, id: 3xk5q, df_shape: (3, 12)
#363, id: fst40, df_shape: (20, 12)
#364, id: ev65n, df_shape: (30, 12)
#365, id: mpyx5, df_shape: (3, 12)
#366, id: t5ud1, df_shape: (55, 12)
#367, id: r3mr7, df_shape: (20, 12)
#368, id: lb1ty, df_shape: (8, 12)
#369, id: qf4ed, df_shape: (218, 12)
#370, id: gng7s, df_shape: (7, 12)
#371, id: a49o1, df_shape: (21, 12)
#372, id: dkupk, df_shape: (25, 12)
#373, id: q0jqs, df_shape: (368, 12)
#374, id: owmbw, df_shape: (9, 12)
#375, id: wcpia, df_shape: (86, 12)
#376, id: j9bji, df_shape: (11, 12)
#377, id: cqb50, df_shape: (1153, 12)
#378, id: 368qw, df_shape: (43, 12)
#379, id: 2n552, df_shape: (26, 12)
#380, id: e5hx4, df_shape: (3, 12)
#381, id: n94yh, df_shape: (187, 12)
#382, id: ermkj, df_shape: (14, 12)
#383, id: bemxq, df_shape: (410, 12)
#384, id: zlhr5, df_shape: (3, 12)
#385, id: x57kj, df_shape: (180, 12)
#386, id: l3q2c, df_shape: (31, 12)
#387, id: n7ohe, df_shape: (5, 12)
#388, id: 334sj, df_shape: (492, 12)
#389, id: pxojc, df_shape: (1, 12)
#390, id: h35ob, df_shape: (6, 12)
#391, id: yv4i8, df_shape: (131, 12)
#392, id: t6bjx, df_shape: (18, 12)
#393, id: fiaxj, df_shape: (4, 12)
#394, id: embgu, df_shape: (841, 12)
#395, id: xraq0, df_shape: (47, 12)
#396, id: 7fvuz, df_shape: (111, 12)
#397, id: l4k4g, df_shape: (22, 12)
#398, id: tf3ny, df_shape: (7, 12)
#399, id: ab4i4, df_shape: (9, 12)
#400, id: 13ks8, df_shape: (25, 12)
#401, id: uwfbz, df_shape: (50, 12)
#402, id: 7xcrw, df_shape: (52, 12)
#403, id: 8v721, df_shape: (79, 12)
#404, id: yatfx, df_shape: (1101, 12)
#405, id: 0ihb1, df_shape: (4, 12)
#406, id: 7iarh, df_shape: (8, 12)
#407, id: lj44r, df_shape: (382, 12)
#408, id: u1boo, df_shape: (7, 12)
#409, id: mybql, df_shape: (17, 12)
#410, id: hr5ck, df_shape: (1, 12)
#411, id: uy0bv, df_shape: (51, 12)
#412, id: ivo0z, df_shape: (163, 12)
#413, id: 46wc7, df_shape: (1, 12)
#414, id: nk8vd, df_shape: (282, 12)
#415, id: c7lrm, df_shape: (14, 12)
#416, id: 6dlmt, df_shape: (553, 12)
#417, id: 1m1qq, df_shape: (407, 12)
#418, id: 2nmr6, df_shape: (2, 12)
#419, id: zmyhq, df_shape: (1, 12)
#420, id: npotf, df_shape: (5, 12)
#421, id: sy7to, df_shape: (5, 12)
#422, id: 6v22z, df_shape: (12, 12)
#423, id: lk0hr, df_shape: (3, 12)
#424, id: wjb59, df_shape: (32, 12)
#425, id: d6hvb, df_shape: (66, 12)
#426, id: pzzd5, df_shape: (66, 12)
#427, id: 7ugtp, df_shape: (1611, 12)
#428, id: 87hba, df_shape: (397, 12)
#429, id: dvwey, df_shape: (388, 12)
#430, id: asxv3, df_shape: (90, 12)
#431, id: zl0i9, df_shape: (13, 12)
#432, id: 74uth, df_shape: (860, 12)
#433, id: tr8gr, df_shape: (4789, 12)
#434, id: mx93y, df_shape: (3, 12)
#435, id: bdh1w, df_shape: (11, 12)
#436, id: n8ad4, df_shape: (18, 12)
#437, id: tvcge, df_shape: (18, 12)
#438, id: kiy8a, df_shape: (48, 12)
#439, id: xuhv6, df_shape: (13, 12)
#440, id: u1tlx, df_shape: (23, 12)
#441, id: ujzic, df_shape: (2, 12)
#442, id: ewuji, df_shape: (48, 12)
#443, id: ujlwm, df_shape: (22, 12)
#444, id: xrvl5, df_shape: (41, 12)
#445, id: usz88, df_shape: (124, 12)
#446, id: 381sk, df_shape: (618, 12)
#447, id: gq4ft, df_shape: (841, 12)
#448, id: bgnwc, df_shape: (45, 12)
#449, id: xepz5, df_shape: (2, 12)
#450, id: bsd2s, df_shape: (15, 12)
#451, id: 6y9fi, df_shape: (13, 12)
#452, id: 65mfl, df_shape: (10, 12)
#453, id: s6ltb, df_shape: (2, 12)
#454, id: e38pm, df_shape: (14, 12)
#455, id: 2k41d, df_shape: (5, 12)

#456, id: fu77m, df_shape: (29, 12)
#457, id: 11ru8, df_shape: (37, 12)
#458, id: fk9cd, df_shape: (14, 12)
#459, id: zq6b7, df_shape: (545, 12)
#460, id: 3yjw5, df_shape: (43, 12)
#461, id: xtad5, df_shape: (14, 12)
#462, id: qk8g4, df_shape: (231, 12)
#463, id: vpi2b, df_shape: (216, 12)
#464, id: j7mwe, df_shape: (15, 12)
#465, id: icrd8, df_shape: (5, 12)
#466, id: plwxv, df_shape: (10, 12)
#467, id: ay01i, df_shape: (37, 12)
#468, id: jwr6k, df_shape: (4, 12)
#469, id: 43bxz, df_shape: (13, 12)
#470, id: mk8s4, df_shape: (118, 12)
#471, id: 2f5j0, df_shape: (78, 12)
#472, id: ukv1w, df_shape: (9, 12)
#473, id: z0z9i, df_shape: (36, 12)
#474, id: t0a3s, df_shape: (45, 12)
#475, id: u10pc, df_shape: (1, 12)
#476, id: jna3v, df_shape: (33, 12)
#477, id: 5z4h6, df_shape: (8, 12)
#478, id: pp70n, df_shape: (35, 12)
#479, id: ffqxw, df_shape: (5, 12)
#480, id: 93swq, df_shape: (1, 12)
#481, id: eqr03, df_shape: (5, 12)
#482, id: kqb1i, df_shape: (1, 12)
#483, id: rha7f, df_shape: (73, 12)
#484, id: nqt6r, df_shape: (8, 12)
#485, id: 65pjf, df_shape: (39, 12)
#486, id: sdvml, df_shape: (1, 12)
#487, id: 5kgq5, df_shape: (128, 12)
#488, id: u18eg, df_shape: (142, 12)
#489, id: fz81a, df_shape: (12, 12)
#490, id: ezsqe, df_shape: (6, 12)
#491, id: 98qns, df_shape: (5, 12)
#492, id: fvwej, df_shape: (22, 12)
#493, id: ia3uf, df_shape: (173, 12)
#494, id: ufnn2, df_shape: (2, 12)
#495, id: xzkx2, df_shape: (183, 12)
#496, id: yyohv, df_shape: (10, 12)
#497, id: o12fx, df_shape: (10, 12)
#498, id: nopbk, df_shape: (44, 12)
#499, id: 7cf10, df_shape: (132, 12)
#500, id: u3p81, df_shape: (2, 12)
#501, id: et2f1, df_shape: (2, 12)
#502, id: h0bzv, df_shape: (17, 12)
#503, id: vnwd1, df_shape: (2, 12)
#504, id: h6ssi, df_shape: (1, 12)
#505, id: aonog, df_shape: (32, 12)
#506, id: 9l7p5, df_shape: (5, 12)
#507, id: 166rq, df_shape: (2, 12)
#508, id: jygw8, df_shape: (121, 12)
#509, id: 2rv1n, df_shape: (5, 12)
#510, id: 3x2zb, df_shape: (10, 12)
#511, id: t1qql, df_shape: (192, 12)
#512, id: hj2xe, df_shape: (3, 12)
#513, id: b4o0z, df_shape: (1, 12)
#514, id: 0w5bn, df_shape: (2, 12)
#515, id: 97wfe, df_shape: (34, 12)
#516, id: vu7re, df_shape: (2, 12)
#517, id: ngks2, df_shape: (11, 12)
#518, id: 6gslt, df_shape: (66, 12)
#519, id: ehyaj, df_shape: (8, 12)
#520, id: w1guw, df_shape: (7, 12)
#521, id: 4rn16, df_shape: (10, 12)
#522, id: jz085, df_shape: (18, 12)
#523, id: wqiq1, df_shape: (4, 12)
#524, id: 84m2r, df_shape: (8, 12)
#525, id: phn6z, df_shape: (23, 12)
#526, id: 3sn39, df_shape: (20, 12)
#527, id: 3o1xh, df_shape: (8, 12)
#528, id: h6s97, df_shape: (1, 12)
#529, id: tegjb, df_shape: (42, 12)
#530, id: k9200, df_shape: (55, 12)
#531, id: hyo7u, df_shape: (7, 12)
#532, id: avlv9, df_shape: (46, 12)
#533, id: p2z07, df_shape: (9, 12)
#534, id: peo9u, df_shape: (5, 12)
#535, id: 8p4dr, df_shape: (2, 12)
#536, id: 4uvme, df_shape: (11, 12)
#537, id: vpbrj, df_shape: (7, 12)
#538, id: a63t2, df_shape: (5, 12)
#539, id: lf5kg, df_shape: (4, 12)
#540, id: wjics, df_shape: (163, 12)
#541, id: 6vpze, df_shape: (24, 12)
#542, id: og7zn, df_shape: (87, 12)
#543, id: 6u4fi, df_shape: (2, 12)
#544, id: 3dtoa, df_shape: (2, 12)
#545, id: jtxiv, df_shape: (354, 12)
#546, id: wwh58, df_shape: (20, 12)
#547, id: 81d3t, df_shape: (96, 12)
#548, id: 87hwv, df_shape: (5, 12)
#549, id: xvgwt, df_shape: (5, 12)
#550, id: e87qz, df_shape: (47, 12)
#551, id: ugkkm, df_shape: (3, 12)
#552, id: fi7d7, df_shape: (3, 12)
#553, id: q1inh, df_shape: (5, 12)
#554, id: sfsca, df_shape: (1, 12)
#555, id: 7pi80, df_shape: (123, 12)
#556, id: wjfln, df_shape: (8, 12)
#557, id: uqflu, df_shape: (1, 12)
#558, id: g26sr, df_shape: (1183, 12)
#559, id: ioz85, df_shape: (1, 12)
#560, id: 91qrt, df_shape: (4, 12)
#561, id: rv5l8, df_shape: (5, 12)
#562, id: e8gs5, df_shape: (4, 12)
#563, id: sthwg, df_shape: (6, 12)
#564, id: jxh0l, df_shape: (1, 12)
#565, id: mob55, df_shape: (9, 12)
#566, id: sm1id, df_shape: (4, 12)
#567, id: dsmcj, df_shape: (195, 12)
#568, id: hgzwp, df_shape: (7, 12)
#569, id: 2ndn1, df_shape: (1, 12)
#570, id: 0ux86, df_shape: (8, 12)
#571, id: u60if, df_shape: (1, 12)
#572, id: 4n6t5, df_shape: (6, 12)
#573, id: nnfrg, df_shape: (4, 12)
#574, id: y7u58, df_shape: (16, 12)
#575, id: h3slg, df_shape: (4, 12)
#576, id: l0j1z, df_shape: (5, 12)
#577, id: zkd58, df_shape: (4, 12)
#578, id: pfoty, df_shape: (7, 12)
#579, id: 33btl, df_shape: (1, 12)
#580, id: g7kc0, df_shape: (3, 12)
#581, id: o4u3t, df_shape: (72, 12)
#582, id: s4604, df_shape: (77, 12)
#583, id: u8gc2, df_shape: (15, 12)
#584, id: ufedn, df_shape: (2, 12)
#585, id: 9q5er, df_shape: (9, 12)
#586, id: 3vz7l, df_shape: (7, 12)
#587, id: g5oc4, df_shape: (13, 12)
#588, id: xn35o, df_shape: (1, 12)
#589, id: l09cv, df_shape: (3, 12)
#590, id: n4e6l, df_shape: (3, 12)
#591, id: gi05a, df_shape: (7059, 12)
#592, id: jb30k, df_shape: (1, 12)
#593, id: qhkdw, df_shape: (2, 12)
#594, id: torbm, df_shape: (3, 12)
#595, id: 3vi4t, df_shape: (2249, 12)
#596, id: wa00e, df_shape: (213, 12)
#597, id: sxpnh, df_shape: (206, 12)
#598, id: 012wh, df_shape: (3374, 12)
#599, id: rxz6x, df_shape: (607, 12)
#600, id: h1ko2, df_shape: (11917, 12)
#601, id: ea3xj, df_shape: (27, 12)
#602, id: 5omjo, df_shape: (21, 12)
#603, id: gfsi7, df_shape: (4722, 12)
#604, id: jwlsl, df_shape: (66, 12)
#605, id: peotc, df_shape: (23, 12)
#606, id: x0bn4, df_shape: (2059, 12)
#607, id: 2yowp, df_shape: (3468, 12)
#608, id: t9wow, df_shape: (185, 12)
#609, id: 8l8yj, df_shape: (290, 12)
#610, id: 300ho, df_shape: (104, 12)
#611, id: o7tsy, df_shape: (33, 12)
#612, id: n5ktl, df_shape: (16, 12)
#613, id: pnclx, df_shape: (370, 12)
#614, id: jhm20, df_shape: (2772, 12)
#615, id: fbzme, df_shape: (84, 12)
#616, id: 98hw1, df_shape: (44, 12)
#617, id: 6enkh, df_shape: (1542, 12)
#618, id: jklnk, df_shape: (41, 12)
#619, id: cwiym, df_shape: (163, 12)
#620, id: ndb8t, df_shape: (549, 12)
#621, id: 6inq4, df_shape: (504, 12)
#622, id: ii5g0, df_shape: (296, 12)
#623, id: pb7qv, df_shape: (40, 12)
#624, id: i1aya, df_shape: (10070, 12)
#625, id: c6lgj, df_shape: (12, 12)
#626, id: 4qf7m, df_shape: (556, 12)
#627, id: augzq, df_shape: (198, 12)
#628, id: cre3h, df_shape: (138, 12)
#629, id: 8hp9m, df_shape: (7938, 12)
#630, id: diwoh, df_shape: (2634, 12)
#631, id: smimc, df_shape: (6, 12)
#632, id: s4yrw, df_shape: (947, 12)
#633, id: 97m4q, df_shape: (443, 12)
#634, id: bc85n, df_shape: (155, 12)
#635, id: fn6fr, df_shape: (1357, 12)
#636, id: yuokv, df_shape: (1352, 12)
#637, id: mqgy5, df_shape: (439, 12)
#638, id: im3yk, df_shape: (7946, 12)
#639, id: v1s4p, df_shape: (1211, 12)
#640, id: 7pu6b, df_shape: (2092, 12)
#641, id: gl1rx, df_shape: (20, 12)
#642, id: fnetm, df_shape: (266, 12)
#643, id: zo1p3, df_shape: (453, 12)
#644, id: pov36, df_shape: (542, 12)
#645, id: ubf0z, df_shape: (89, 12)
#646, id: hfwg0, df_shape: (1324, 12)
#647, id: ng9qq, df_shape: (1467, 12)
#648, id: 2uu2n, df_shape: (8819, 12)
#649, id: k8wgt, df_shape: (256, 12)
#650, id: wxfr0, df_shape: (166, 12)
#651, id: lojej, df_shape: (62, 12)
#652, id: 5ny8k, df_shape: (2993, 12)
#653, id: 4gldi, df_shape: (646, 12)
#654, id: mrhzq, df_shape: (43, 12)
#655, id: 85oc6, df_shape: (224, 12)
#656, id: h6418, df_shape: (198, 12)
#657, id: 50v4n, df_shape: (62, 12)
#658, id: ve6a9, df_shape: (735, 12)
#659, id: i6t2q, df_shape: (5631, 12)
#660, id: toaj7, df_shape: (2397, 12)
#661, id: 8fqx4, df_shape: (2882, 12)
#662, id: bstmq, df_shape: (1522, 12)
#663, id: xym5u, df_shape: (1213, 12)
#664, id: e71t5, df_shape: (18, 12)
#665, id: 7hpsl, df_shape: (4016, 12)
#666, id: yhoht, df_shape: (2549, 12)
#667, id: ay5c0, df_shape: (18, 12)
#668, id: ozx86, df_shape: (12, 12)
#669, id: 73dk7, df_shape: (104, 12)
#670, id: nhd7f, df_shape: (203, 12)
#671, id: dt5o5, df_shape: (486, 12)
#672, id: 4dyrq, df_shape: (3024, 12)
#673, id: loo2y, df_shape: (629, 12)
#674, id: 11oce, df_shape: (698, 12)
#675, id: kvb6s, df_shape: (852, 12)
#676, id: c4boy, df_shape: (844, 12)
#677, id: giskf, df_shape: (1322, 12)
#678, id: b08hq, df_shape: (112, 12)
#679, id: w3yu4, df_shape: (469, 12)
#680, id: 9mnih, df_shape: (148, 12)
#681, id: uax6v, df_shape: (556, 12)
#682, id: y53wq, df_shape: (168, 12)

#683, id: 2q4bg, df_shape: (169, 12)
#684, id: mig9v, df_shape: (74, 12)
#685, id: 1l64e, df_shape: (596, 12)
#686, id: 18mig, df_shape: (352, 12)
#687, id: uk4ci, df_shape: (1772, 12)
#688, id: 60iru, df_shape: (1482, 12)
#689, id: xsfsr, df_shape: (203, 12)
#690, id: rlvys, df_shape: (63, 12)
#691, id: svnjk, df_shape: (236, 12)
#692, id: v6c1z, df_shape: (178, 12)
#693, id: 4tpwq, df_shape: (176, 12)
#694, id: viwte, df_shape: (881, 12)
#695, id: ijsrn, df_shape: (184, 12)
#696, id: dvxvy, df_shape: (132, 12)
#697, id: g4cv3, df_shape: (220, 12)
#698, id: wkqfj, df_shape: (161, 12)
#699, id: 9h1wk, df_shape: (42, 12)
#700, id: f8iux, df_shape: (411, 12)
#701, id: bggqz, df_shape: (832, 12)
#702, id: 2hc33, df_shape: (236, 12)
#703, id: fn5ar, df_shape: (782, 12)
#704, id: u0ce6, df_shape: (129, 12)
#705, id: iq5be, df_shape: (275, 12)
#706, id: 941z7, df_shape: (143, 12)
#707, id: 4ksf7, df_shape: (228, 12)
#708, id: rf8x6, df_shape: (22, 12)
#709, id: krz34, df_shape: (83, 12)
#710, id: z1ujg, df_shape: (15, 12)
#711, id: s5mio, df_shape: (255, 12)
#712, id: b189z, df_shape: (144, 12)
#713, id: agzbu, df_shape: (261, 12)
#714, id: l14ty, df_shape: (238, 12)
#715, id: owu7b, df_shape: (409, 12)
#716, id: 9zru2, df_shape: (265, 12)
#717, id: 5353u, df_shape: (141, 12)
#718, id: yeqhb, df_shape: (26, 12)
#719, id: kh5nz, df_shape: (1323, 12)
#720, id: g40lj, df_shape: (126, 12)
#721, id: ep2gq, df_shape: (278, 12)
#722, id: t0oxy, df_shape: (141, 12)
#723, id: swpg7, df_shape: (91, 12)
#724, id: rp4kn, df_shape: (524, 12)
#725, id: 6ltba, df_shape: (6, 12)
#726, id: n68mr, df_shape: (76, 12)
#727, id: 5jpjc, df_shape: (52, 12)
#728, id: dop6z, df_shape: (579, 12)
#729, id: khgus, df_shape: (2813, 12)
#730, id: 9366k, df_shape: (188, 12)
#731, id: 8zp11, df_shape: (177, 12)
#732, id: 850sq, df_shape: (122, 12)
#733, id: y8jqm, df_shape: (81, 12)
#734, id: ysdfv, df_shape: (98, 12)
#735, id: a1xum, df_shape: (420, 12)
#736, id: ff3lz, df_shape: (2515, 12)
#737, id: qp6cy, df_shape: (431, 12)
#738, id: atbz4, df_shape: (103, 12)
#739, id: dz139, df_shape: (121, 12)
#740, id: 4y4k9, df_shape: (651, 12)
#741, id: wted2, df_shape: (296, 12)
#742, id: z9whw, df_shape: (1, 12)
#743, id: zx5nm, df_shape: (41, 12)
#744, id: o8bjx, df_shape: (71, 12)
#745, id: 1d9lx, df_shape: (47, 12)
#746, id: afx7u, df_shape: (249, 12)
#747, id: 2e8gt, df_shape: (177, 12)
#748, id: nv3ua, df_shape: (22, 12)
#749, id: lqqkl, df_shape: (25, 12)
#750, id: 51rwd, df_shape: (185, 12)
#751, id: 2dfh7, df_shape: (1310, 12)
#752, id: qj8uk, df_shape: (1067, 12)
#753, id: ocrhn, df_shape: (217, 12)
#754, id: zw2xg, df_shape: (622, 12)
#755, id: rdekv, df_shape: (270, 12)
#756, id: tg4rn, df_shape: (369, 12)
#757, id: tdhs8, df_shape: (204, 12)
#758, id: htiyi, df_shape: (222, 12)
#759, id: 7zyk3, df_shape: (178, 12)
#760, id: befuo, df_shape: (638, 12)
#761, id: lae7k, df_shape: (1827, 12)
#762, id: cy9ws, df_shape: (1390, 12)
#763, id: d4xlc, df_shape: (33, 12)
#764, id: yb4ny, df_shape: (210, 12)
#765, id: ystf8, df_shape: (20, 12)
#766, id: j4ri3, df_shape: (242, 12)
#767, id: gemkd, df_shape: (242, 12)
#768, id: lnynx, df_shape: (323, 12)
#769, id: ewmzr, df_shape: (1263, 12)
#770, id: whw12, df_shape: (151, 12)
#771, id: r7u5i, df_shape: (410, 12)
#772, id: 8s0kd, df_shape: (50, 12)
#773, id: ovo23, df_shape: (49, 12)
#774, id: 99clj, df_shape: (164, 12)
#775, id: t79cc, df_shape: (28, 12)
#776, id: fr0r6, df_shape: (245, 12)
#777, id: fedfm, df_shape: (6772, 12)
#778, id: y4wts, df_shape: (16, 12)
#779, id: 0leyt, df_shape: (394, 12)
#780, id: ewpkc, df_shape: (76, 12)
#781, id: k6snz, df_shape: (182, 12)
#782, id: q8reu, df_shape: (117, 12)
#783, id: y18s4, df_shape: (167, 12)
#784, id: anob2, df_shape: (28, 12)
#785, id: q6j27, df_shape: (107, 12)
#786, id: guub6, df_shape: (317, 12)
#787, id: 70l1u, df_shape: (616, 12)
#788, id: b0oj7, df_shape: (19, 12)
#789, id: vf115, df_shape: (75, 12)
#790, id: t17jq, df_shape: (15, 12)
#791, id: c9khk, df_shape: (14, 12)
#792, id: nldvu, df_shape: (13, 12)
#793, id: 6kegp, df_shape: (27, 12)
#794, id: pyq31, df_shape: (34, 12)
#795, id: acbql, df_shape: (12, 12)
#796, id: f6tcc, df_shape: (430, 12)
#797, id: f94nb, df_shape: (231, 12)
#798, id: vkd6f, df_shape: (46, 12)
#799, id: 0rydp, df_shape: (331, 12)
#800, id: rwc0q, df_shape: (403, 12)
#801, id: pyy8k, df_shape: (193, 12)
#802, id: 31hfq, df_shape: (59, 12)
#803, id: h7fdx, df_shape: (100, 12)
#804, id: ad81i, df_shape: (388, 12)
#805, id: rgd0k, df_shape: (89, 12)
#806, id: s4bjy, df_shape: (35, 12)
#807, id: xwvay, df_shape: (138, 12)
#808, id: qb9ad, df_shape: (60, 12)
#809, id: dk79x, df_shape: (18, 12)
#810, id: 3s2u1, df_shape: (382, 12)
#811, id: f7d2z, df_shape: (330, 12)
#812, id: jed37, df_shape: (104, 12)
#813, id: 7n6dw, df_shape: (903, 12)
#814, id: aiap1, df_shape: (1188, 12)
#815, id: a3929, df_shape: (212, 12)
#816, id: t09a8, df_shape: (23, 12)
#817, id: toxfq, df_shape: (2598, 12)
#818, id: ryp4f, df_shape: (119, 12)
#819, id: ep52o, df_shape: (19, 12)
#820, id: zxlrd, df_shape: (237, 12)
#821, id: tsj82, df_shape: (11, 12)
#822, id: xbybt, df_shape: (78, 12)
#823, id: yysd7, df_shape: (83, 12)
#824, id: mmby1, df_shape: (322, 12)
#825, id: h7y2q, df_shape: (59, 12)
#826, id: 5m2x6, df_shape: (771, 12)
#827, id: 6hevb, df_shape: (2223, 12)
#828, id: 0fbzo, df_shape: (324, 12)
#829, id: v2q4u, df_shape: (32, 12)
#830, id: pkmm6, df_shape: (617, 12)
#831, id: ulogz, df_shape: (266, 12)
#832, id: bhx4t, df_shape: (235, 12)
#833, id: oqev2, df_shape: (323, 12)
#834, id: 8t2z8, df_shape: (232, 12)
#835, id: qt94q, df_shape: (470, 12)
#836, id: 99smf, df_shape: (68, 12)
#837, id: de1fg, df_shape: (75, 12)
#838, id: ko2gr, df_shape: (138, 12)
#839, id: t5zug, df_shape: (14, 12)
#840, id: wpchh, df_shape: (171, 12)
#841, id: a1erg, df_shape: (38, 12)
#842, id: cu9dk, df_shape: (130, 12)
#843, id: cf3pw, df_shape: (5657, 12)
#844, id: 88xe3, df_shape: (1296, 12)
#845, id: sg8yd, df_shape: (180, 12)
#846, id: 9mlwl, df_shape: (317, 12)
#847, id: lj5l0, df_shape: (289, 12)
#848, id: u06av, df_shape: (34, 12)
#849, id: thyqa, df_shape: (75, 12)
#850, id: 72ygv, df_shape: (1101, 12)
#851, id: lqpns, df_shape: (860, 12)
#852, id: phbnm, df_shape: (177, 12)
#853, id: 6d6zh, df_shape: (521, 12)
#854, id: p142v, df_shape: (141, 12)
#855, id: kzsta, df_shape: (93, 12)
#856, id: ai1dg, df_shape: (23, 12)
#857, id: fopa7, df_shape: (42, 12)
#858, id: 7jkj3, df_shape: (80, 12)
#859, id: 6jj4e, df_shape: (1142, 12)
#860, id: u8j4c, df_shape: (1, 12)
#861, id: yb239, df_shape: (14, 12)
#862, id: tuv9k, df_shape: (46, 12)
#863, id: baaje, df_shape: (100, 12)
#864, id: pg37c, df_shape: (259, 12)
#865, id: gcqyg, df_shape: (6, 12)
#866, id: ujy3w, df_shape: (175, 12)
#867, id: 9bkrl, df_shape: (860, 12)
#868, id: 7vgew, df_shape: (12, 12)
#869, id: 4u1b5, df_shape: (5, 12)
#870, id: 1y8ds, df_shape: (523, 12)
#871, id: 9h3cd, df_shape: (22, 12)
#872, id: pfa9f, df_shape: (139, 12)
#873, id: ex89p, df_shape: (21, 12)
#874, id: 3k1kz, df_shape: (209, 12)
#875, id: tpe57, df_shape: (349, 12)
#876, id: vvt9s, df_shape: (12, 12)
#877, id: ufk7p, df_shape: (1406, 12)
#878, id: 5aaba, df_shape: (10, 12)
#879, id: k8tci, df_shape: (117, 12)
#880, id: sugxk, df_shape: (12, 12)
#881, id: ucdtj, df_shape: (388, 12)
#882, id: cg8j4, df_shape: (47, 12)
#883, id: qzvsr, df_shape: (7, 12)
#884, id: 51ekz, df_shape: (173, 12)
#885, id: w12fm, df_shape: (6, 12)
#886, id: dlm1c, df_shape: (104, 12)
#887, id: 403fj, df_shape: (33, 12)
#888, id: 0gblu, df_shape: (367, 12)
#889, id: e193f, df_shape: (25, 12)
#890, id: ay2d4, df_shape: (2, 12)
#891, id: h3apd, df_shape: (527, 12)
#892, id: 5cm8u, df_shape: (153, 12)
#893, id: 2u1hj, df_shape: (21, 12)
#894, id: 8qe4w, df_shape: (60, 12)
#895, id: mesze, df_shape: (351, 12)
#896, id: b9h4c, df_shape: (396, 12)
#897, id: 5kj2r, df_shape: (788, 12)
#898, id: srvch, df_shape: (409, 12)
#899, id: di5cl, df_shape: (483, 12)
#900, id: nmhpg, df_shape: (276, 12)
#901, id: b5poi, df_shape: (282, 12)
#902, id: o1sci, df_shape: (108, 12)
#903, id: 1i64b, df_shape: (1, 12)
#904, id: tmy8p, df_shape: (7, 12)
#905, id: otczn, df_shape: (74, 12)
#906, id: aml8q, df_shape: (46, 12)

#907, id: mflvb, df_shape: (114, 12)
#908, id: ro20d, df_shape: (17, 12)
#909, id: 8s353, df_shape: (59, 12)
#910, id: sgzj8, df_shape: (439, 12)
#911, id: rgejo, df_shape: (34, 12)
#912, id: d17g8, df_shape: (46, 12)
#913, id: a7zfi, df_shape: (58, 12)
#914, id: gawcq, df_shape: (240, 12)
#915, id: 5frsr, df_shape: (1582, 12)
#916, id: jvy9s, df_shape: (303, 12)
#917, id: ye0sm, df_shape: (258, 12)
#918, id: 67f2r, df_shape: (153, 12)
#919, id: ol8tt, df_shape: (144, 12)
#920, id: 7a3vn, df_shape: (222, 12)
#921, id: x7559, df_shape: (21, 12)
#922, id: 01b3e, df_shape: (27, 12)
#923, id: 37pc6, df_shape: (18, 12)
#924, id: fnuq7, df_shape: (3, 12)
#925, id: oqmuc, df_shape: (68, 12)
#926, id: fyli7, df_shape: (1472, 12)
#927, id: ahcgv, df_shape: (122, 12)
#928, id: tw5gw, df_shape: (116, 12)
#929, id: a7s6g, df_shape: (432, 12)
#930, id: sdxtz, df_shape: (65, 12)
#931, id: 46mgt, df_shape: (161, 12)
#932, id: 6olzr, df_shape: (324, 12)
#933, id: bvnx0, df_shape: (82, 12)
#934, id: m24kv, df_shape: (434, 12)
#935, id: dh43q, df_shape: (159, 12)
#936, id: iwjnk, df_shape: (139, 12)
#937, id: 6nof1, df_shape: (123, 12)
#938, id: y09td, df_shape: (261, 12)
#939, id: 5o7w3, df_shape: (65, 12)
#940, id: k5e3t, df_shape: (262, 12)
#941, id: ygnh6, df_shape: (1281, 12)
#942, id: v23z6, df_shape: (7, 12)
#943, id: 523l1, df_shape: (4, 12)
#944, id: ncz6r, df_shape: (27, 12)
#945, id: 526yn, df_shape: (25, 12)
#946, id: 78i4o, df_shape: (82, 12)
#947, id: a5bw6, df_shape: (709, 12)
#948, id: 2y8a3, df_shape: (870, 12)
#949, id: a7wo8, df_shape: (36, 12)
#950, id: 0nlte, df_shape: (35, 12)
#951, id: nk11k, df_shape: (58, 12)
#952, id: 13gi4, df_shape: (104, 12)
#953, id: 407p7, df_shape: (84, 12)
#954, id: a1nxv, df_shape: (165, 12)
#955, id: uav3w, df_shape: (51, 12)
#956, id: r4w6c, df_shape: (177, 12)
#957, id: lms74, df_shape: (4, 12)
#958, id: 00hjy, df_shape: (25, 12)
#959, id: a2ngx, df_shape: (6, 12)
#960, id: k1rsw, df_shape: (37, 12)
#961, id: 8ywoe, df_shape: (47, 12)
#962, id: s6d69, df_shape: (63, 12)
#963, id: u3wxo, df_shape: (153, 12)
#964, id: fi8mh, df_shape: (68, 12)
#965, id: xhkkh, df_shape: (12, 12)
#966, id: kpr78, df_shape: (112, 12)
#967, id: tt6db, df_shape: (156, 12)
#968, id: ldi0g, df_shape: (15, 12)
#969, id: 6ma0q, df_shape: (36, 12)
#970, id: acnwd, df_shape: (40, 12)
#971, id: r1wfm, df_shape: (184, 12)
#972, id: 85k6u, df_shape: (23, 12)
#973, id: dntfm, df_shape: (53, 12)
#974, id: za24u, df_shape: (89, 12)
#975, id: qzcza, df_shape: (109, 12)
#976, id: 2q68c, df_shape: (11, 12)
#977, id: ijzo9, df_shape: (26, 12)
#978, id: k169w, df_shape: (404, 12)
#979, id: d8p1b, df_shape: (17, 12)
#980, id: v3fz5, df_shape: (10, 12)
#981, id: xowfr, df_shape: (18, 12)
#982, id: iikzq, df_shape: (1329, 12)
#983, id: svazn, df_shape: (22, 12)
#984, id: 9te7w, df_shape: (143, 12)
#985, id: ozdab, df_shape: (252, 12)
#986, id: vd4ls, df_shape: (16, 12)
#987, id: guasz, df_shape: (104, 12)
#988, id: rsvsf, df_shape: (283, 12)
#989, id: fe96d, df_shape: (227, 12)
#990, id: pj841, df_shape: (934, 12)
#991, id: 40r8a, df_shape: (16, 12)
#992, id: acrfr, df_shape: (19, 12)
#993, id: cpy6x, df_shape: (8, 12)
#994, id: 0tx83, df_shape: (343, 12)
#995, id: why08, df_shape: (151, 12)
#996, id: h0c8o, df_shape: (69, 12)
#997, id: w9e6z, df_shape: (332, 12)
#998, id: c58pw, df_shape: (835, 12)
#999, id: f1fau, df_shape: (91, 12)
#1000, id: 3gbey, df_shape: (28, 12)
#1001, id: 0gu9t, df_shape: (25, 12)
#1002, id: hhgnu, df_shape: (129, 12)
#1003, id: 7eome, df_shape: (119, 12)
#1004, id: st6pg, df_shape: (8, 12)
#1005, id: hu49k, df_shape: (111, 12)
#1006, id: uw3sx, df_shape: (2770, 12)
#1007, id: h20je, df_shape: (121, 12)
#1008, id: yzn1e, df_shape: (251, 12)
#1009, id: sy1q3, df_shape: (11, 12)
#1010, id: va739, df_shape: (72, 12)
#1011, id: 9eqmv, df_shape: (144, 12)
#1012, id: yhl1m, df_shape: (959, 12)
#1013, id: wp57x, df_shape: (5110, 12)
#1014, id: xm9u9, df_shape: (115, 12)
#1015, id: zrx1e, df_shape: (132, 12)
#1016, id: 04b66, df_shape: (154, 12)
#1017, id: rb3ly, df_shape: (147, 12)
#1018, id: tvqxk, df_shape: (3422, 12)
#1019, id: m6115, df_shape: (59, 12)
#1020, id: x9k4l, df_shape: (26, 12)
#1021, id: j41vb, df_shape: (68, 12)
#1022, id: 8m6y1, df_shape: (7976, 12)
#1023, id: kb74u, df_shape: (702, 12)
#1024, id: 1z4m8, df_shape: (11397, 12)
#1025, id: qho91, df_shape: (966, 12)
#1026, id: d670w, df_shape: (506, 12)
#1027, id: 210e6, df_shape: (37, 12)
#1028, id: 588xy, df_shape: (34, 12)
#1029, id: t99yr, df_shape: (1081, 12)
#1030, id: 0wbi1, df_shape: (438, 12)
#1031, id: ni4dc, df_shape: (51, 12)
#1032, id: pjm30, df_shape: (3, 12)
#1033, id: vgpug, df_shape: (118, 12)
#1034, id: 9rr5o, df_shape: (12, 12)
#1035, id: xpr53, df_shape: (174, 12)
#1036, id: ullzv, df_shape: (5, 12)
#1037, id: qkafx, df_shape: (85, 12)
#1038, id: xfc2b, df_shape: (547, 12)
#1039, id: e14dq, df_shape: (50, 12)
#1040, id: xpw3b, df_shape: (150, 12)
#1041, id: fhngq, df_shape: (17, 12)
#1042, id: 29jce, df_shape: (59, 12)
#1043, id: xig5x, df_shape: (35, 12)
#1044, id: 7bbwd, df_shape: (52, 12)
#1045, id: o925k, df_shape: (38, 12)
#1046, id: ye64c, df_shape: (95, 12)
#1047, id: llvub, df_shape: (41, 12)
#1048, id: j6xul, df_shape: (792, 12)
#1049, id: yg4lo, df_shape: (86, 12)
#1050, id: yv3a3, df_shape: (419, 12)
#1051, id: ci2d7, df_shape: (17, 12)
#1052, id: edtry, df_shape: (33, 12)
#1053, id: 7u60x, df_shape: (89, 12)
#1054, id: b510f, df_shape: (481, 12)
#1055, id: 29ehm, df_shape: (15, 12)
#1056, id: lfz7h, df_shape: (1404, 12)
#1057, id: rn7qu, df_shape: (4, 12)
#1058, id: z4xwd, df_shape: (1790, 12)
#1059, id: xvl1u, df_shape: (79, 12)
#1060, id: 8irza, df_shape: (236, 12)
#1061, id: iadg5, df_shape: (251, 12)
#1062, id: skl3k, df_shape: (59, 12)
#1063, id: xk5nb, df_shape: (239, 12)
#1064, id: ws2id, df_shape: (149, 12)
#1065, id: qy37o, df_shape: (489, 12)
#1066, id: izo0z, df_shape: (176, 12)
#1067, id: q925k, df_shape: (769, 12)
#1068, id: c9rqe, df_shape: (5, 12)
#1069, id: gc5q0, df_shape: (102, 12)
#1070, id: qcppg, df_shape: (1693, 12)
#1071, id: f5f6k, df_shape: (579, 12)
#1072, id: 1w8ei, df_shape: (50, 12)
#1073, id: 3boba, df_shape: (1413, 12)
#1074, id: drs2x, df_shape: (955, 12)
#1075, id: gw1ad, df_shape: (78, 12)
#1076, id: nwikx, df_shape: (481, 12)
#1077, id: whg3f, df_shape: (715, 12)
#1078, id: 130f2, df_shape: (995, 12)
#1079, id: ff6p9, df_shape: (41, 12)
#1080, id: 0s731, df_shape: (1042, 12)
#1081, id: ihgxc, df_shape: (11, 12)
#1082, id: b5jea, df_shape: (4, 12)
#1083, id: fi2zd, df_shape: (124, 12)
#1084, id: 07axb, df_shape: (2784, 12)
#1085, id: mjkhv, df_shape: (37, 12)
#1086, id: b2ddk, df_shape: (10, 12)
#1087, id: yclqb, df_shape: (202, 12)
#1088, id: o58i3, df_shape: (3, 12)
#1089, id: wc64y, df_shape: (121, 12)
#1090, id: 4trnf, df_shape: (202, 12)
#1091, id: wzxtt, df_shape: (12, 12)
#1092, id: e7fur, df_shape: (8, 12)
#1093, id: 9985s, df_shape: (5, 12)
#1094, id: cckjw, df_shape: (13, 12)
#1095, id: 48k18, df_shape: (171, 12)
#1096, id: 8qtjg, df_shape: (2636, 12)
#1097, id: n4z7z, df_shape: (593, 12)
#1098, id: 7yssf, df_shape: (53, 12)
#1099, id: a59py, df_shape: (34, 12)
#1100, id: os5rw, df_shape: (1, 12)
#1101, id: a1b2v, df_shape: (3, 12)
#1102, id: 1reey, df_shape: (164, 12)
#1103, id: bkdgy, df_shape: (15, 12)
#1104, id: 1ok55, df_shape: (3, 12)
#1105, id: dqgmf, df_shape: (1, 12)
#1106, id: n4v5s, df_shape: (3, 12)
#1107, id: z092v, df_shape: (9, 12)
#1108, id: 5v6lz, df_shape: (23, 12)
#1109, id: yf4wl, df_shape: (105, 12)
#1110, id: 910k0, df_shape: (72, 12)
#1111, id: ho0mi, df_shape: (23, 12)
#1112, id: 62t0a, df_shape: (186, 12)
#1113, id: use6s, df_shape: (149, 12)
#1114, id: dunxq, df_shape: (14, 12)
#1115, id: do3nv, df_shape: (53, 12)
#1116, id: ah41j, df_shape: (66, 12)
#1117, id: 408np, df_shape: (65, 12)
#1118, id: lshuu, df_shape: (396, 12)
#1119, id: ouwvc, df_shape: (555, 12)
#1120, id: q2u40, df_shape: (112, 12)
#1121, id: 4300w, df_shape: (21, 12)
#1122, id: f0e46, df_shape: (31, 12)
#1123, id: pzf3p, df_shape: (2, 12)
#1124, id: a3fmi, df_shape: (64, 12)
#1125, id: moeme, df_shape: (563, 12)
#1126, id: vwitx, df_shape: (5, 12)
#1127, id: w5zlr, df_shape: (103, 12)
#1128, id: n6be1, df_shape: (13, 12)

#1129, id: 169lh, df_shape: (2520, 12)
#1130, id: t30q7, df_shape: (446, 12)
#1131, id: iatwf, df_shape: (333, 12)
#1132, id: 67w1g, df_shape: (51, 12)
#1133, id: 1muxk, df_shape: (67, 12)
#1134, id: nubgc, df_shape: (421, 12)
#1135, id: 4vv5t, df_shape: (444, 12)
#1136, id: apltr, df_shape: (189, 12)
#1137, id: dqfxe, df_shape: (156, 12)
#1138, id: uwqbt, df_shape: (164, 12)
#1139, id: ddgk6, df_shape: (252, 12)
#1140, id: 5wzy0, df_shape: (455, 12)
#1141, id: j5cz5, df_shape: (15, 12)
#1142, id: 5evcm, df_shape: (25, 12)
#1143, id: 7m9q3, df_shape: (8, 12)
#1144, id: vobqp, df_shape: (297, 12)
#1145, id: 8qan0, df_shape: (310, 12)
#1146, id: ekodf, df_shape: (690, 12)
#1147, id: gf5h1, df_shape: (113, 12)
#1148, id: igy9b, df_shape: (176, 12)
#1149, id: ic5x5, df_shape: (718, 12)
#1150, id: 10l8g, df_shape: (339, 12)
#1151, id: 8eqy1, df_shape: (66, 12)
#1152, id: j4c2y, df_shape: (177, 12)
#1153, id: vqe7e, df_shape: (301, 12)
#1154, id: qtmwx, df_shape: (611, 12)
#1155, id: 36d2l, df_shape: (23, 12)
#1156, id: p1tlb, df_shape: (4, 12)
#1157, id: ny02b, df_shape: (387, 12)
#1158, id: g39qx, df_shape: (80, 12)
#1159, id: k5nl3, df_shape: (28, 12)
#1160, id: dc6md, df_shape: (224, 12)
#1161, id: xu00j, df_shape: (22, 12)
#1162, id: wscxj, df_shape: (40, 12)
#1163, id: 6gbug, df_shape: (111, 12)
#1164, id: 5llac, df_shape: (369, 12)
#1165, id: l3y5x, df_shape: (455, 12)
#1166, id: i3ssz, df_shape: (208, 12)
#1167, id: r8j4h, df_shape: (10, 12)
#1168, id: 47jkp, df_shape: (30, 12)
#1169, id: e4pqy, df_shape: (33, 12)
#1170, id: lez6c, df_shape: (31, 12)
#1171, id: ca0s3, df_shape: (18, 12)
#1172, id: lre58, df_shape: (51, 12)
#1173, id: 8mp30, df_shape: (1, 12)
#1174, id: h9na3, df_shape: (6, 12)
#1175, id: qt802, df_shape: (16, 12)
#1176, id: 2qgt8, df_shape: (3, 12)
#1177, id: a2wjy, df_shape: (1, 12)
#1178, id: z08hz, df_shape: (65, 12)
#1179, id: bq29a, df_shape: (1, 12)
#1180, id: rwdky, df_shape: (70, 12)
#1181, id: ipg1o, df_shape: (1, 12)
#1182, id: cwdlt, df_shape: (10, 12)
#1183, id: y5aq8, df_shape: (48, 12)
#1184, id: ucb4u, df_shape: (689, 12)
#1185, id: rpx47, df_shape: (11, 12)
#1186, id: d3jcy, df_shape: (15, 12)
#1187, id: qw8d4, df_shape: (19, 12)
#1188, id: zwc27, df_shape: (37, 12)
#1189, id: a7jdu, df_shape: (26, 12)
#1190, id: udb7l, df_shape: (488, 12)
#1191, id: d6sou, df_shape: (66, 12)
#1192, id: s6prh, df_shape: (2, 12)
#1193, id: lapz4, df_shape: (32, 12)
#1194, id: xkq65, df_shape: (100, 12)
#1195, id: z650m, df_shape: (15, 12)
#1196, id: z2r2t, df_shape: (37, 12)
#1197, id: 7ff32, df_shape: (282, 12)
#1198, id: bm1z2, df_shape: (115, 12)
#1199, id: zbpbr, df_shape: (153, 12)
#1200, id: gcwf8, df_shape: (22, 12)
#1201, id: ofkbt, df_shape: (32, 12)
#1202, id: l7r24, df_shape: (60, 12)
#1203, id: bnkht, df_shape: (114, 12)
#1204, id: 7nedy, df_shape: (19, 12)
#1205, id: wrz1m, df_shape: (112, 12)
#1206, id: rjsx8, df_shape: (3138, 12)
#1207, id: qvwgg, df_shape: (5, 12)
#1208, id: l61zc, df_shape: (1275, 12)
#1209, id: 20fsz, df_shape: (1069, 12)
#1210, id: ar3o8, df_shape: (41, 12)
#1211, id: qdhmi, df_shape: (578, 12)
#1212, id: 9yp96, df_shape: (1128, 12)
#1213, id: ks4q8, df_shape: (20, 12)
#1214, id: d05mt, df_shape: (168, 12)
#1215, id: sxko0, df_shape: (1582, 12)
#1216, id: 74thg, df_shape: (557, 12)
#1217, id: opvm0, df_shape: (65, 12)
#1218, id: qdnr2, df_shape: (250, 12)
#1219, id: qfodq, df_shape: (23, 12)
#1220, id: kn2gh, df_shape: (151, 12)
#1221, id: 6vwpa, df_shape: (97, 12)
#1222, id: ahxl0, df_shape: (599, 12)
#1223, id: wuafa, df_shape: (10, 12)
#1224, id: hkzuk, df_shape: (3, 12)
#1225, id: 2a3q8, df_shape: (17, 12)
#1226, id: h2rbu, df_shape: (5, 12)
#1227, id: ixoqw, df_shape: (728, 12)
#1228, id: auqct, df_shape: (290, 12)
#1229, id: brfm1, df_shape: (22, 12)
#1230, id: gle13, df_shape: (173, 12)
#1231, id: bg7gh, df_shape: (230, 12)
#1232, id: 5qgeo, df_shape: (83, 12)
#1233, id: x4fy2, df_shape: (55, 12)
#1234, id: oxbbz, df_shape: (23, 12)
#1235, id: gve5e, df_shape: (9, 12)
#1236, id: r02p2, df_shape: (182, 12)
#1237, id: zk33u, df_shape: (16, 12)
#1238, id: xucqs, df_shape: (31, 12)
#1239, id: vvb6h, df_shape: (811, 12)
#1240, id: mtukx, df_shape: (16, 12)
#1241, id: ex37f, df_shape: (15, 12)
#1242, id: 43e40, df_shape: (20, 12)
#1243, id: czufj, df_shape: (1, 12)
#1244, id: 9810o, df_shape: (28, 12)
#1245, id: euppw, df_shape: (414, 12)
#1246, id: akxgv, df_shape: (221, 12)
#1247, id: 25pmz, df_shape: (74, 12)
#1248, id: anj07, df_shape: (10, 12)
#1249, id: yexz9, df_shape: (24, 12)
#1250, id: 69oo6, df_shape: (30, 12)
#1251, id: h3tia, df_shape: (10, 12)
#1252, id: u0djz, df_shape: (174, 12)
#1253, id: 5suvg, df_shape: (75, 12)
#1254, id: rkj1l, df_shape: (29, 12)
#1255, id: t7tuo, df_shape: (16, 12)
#1256, id: kb0dd, df_shape: (115, 12)
#1257, id: 2t9re, df_shape: (208, 12)
#1258, id: qyhth, df_shape: (138, 12)
#1259, id: 8rfge, df_shape: (5, 12)
#1260, id: teim5, df_shape: (20, 12)
#1261, id: huu09, df_shape: (53, 12)
#1262, id: 12cps, df_shape: (231, 12)
#1263, id: 5shff, df_shape: (185, 12)
#1264, id: enigu, df_shape: (12, 12)
#1265, id: wfoyc, df_shape: (66, 12)
#1266, id: isow0, df_shape: (43, 12)
#1267, id: ieiew, df_shape: (12, 12)
#1268, id: c8jo2, df_shape: (40, 12)
#1269, id: da9yt, df_shape: (264, 12)
#1270, id: f968r, df_shape: (269, 12)
#1271, id: nxakg, df_shape: (568, 12)
#1272, id: 1gtxr, df_shape: (61, 12)
#1273, id: t9a0i, df_shape: (153, 12)
#1274, id: ncpla, df_shape: (3, 12)
#1275, id: 6v7xi, df_shape: (19, 12)
#1276, id: briuk, df_shape: (15, 12)
#1277, id: 227v8, df_shape: (40, 12)
#1278, id: 6jkpf, df_shape: (104, 12)
#1279, id: 26fml, df_shape: (34, 12)
#1280, id: bbptc, df_shape: (29, 12)
#1281, id: uiqjw, df_shape: (19, 12)
#1282, id: xbzjq, df_shape: (49, 12)
#1283, id: y0ijh, df_shape: (17, 12)
#1284, id: vepg8, df_shape: (482, 12)
#1285, id: 3ywts, df_shape: (6, 12)
#1286, id: 9uw3p, df_shape: (4, 12)
#1287, id: uemxf, df_shape: (51, 12)
#1288, id: rju13, df_shape: (8, 12)
#1289, id: vm92o, df_shape: (96, 12)
#1290, id: 2tdw2, df_shape: (55, 12)
#1291, id: 23saj, df_shape: (62, 12)
#1292, id: u747g, df_shape: (28, 12)
#1293, id: noed2, df_shape: (20, 12)
#1294, id: 5ch1i, df_shape: (69, 12)
#1295, id: 0mzuc, df_shape: (73, 12)
#1296, id: k0h6a, df_shape: (1751, 12)
#1297, id: iy1cn, df_shape: (434, 12)
#1298, id: doloy, df_shape: (167, 12)
#1299, id: pq6kj, df_shape: (27, 12)
#1300, id: txda4, df_shape: (735, 12)
#1301, id: mbtfi, df_shape: (231, 12)
#1302, id: 9gfin, df_shape: (33, 12)
#1303, id: ui9zj, df_shape: (36, 12)
#1304, id: 5ruwp, df_shape: (16, 12)
#1305, id: wyedg, df_shape: (6, 12)
#1306, id: y4bhl, df_shape: (19, 12)
#1307, id: b92ak, df_shape: (14, 12)
#1308, id: 3ayg0, df_shape: (54, 12)
#1309, id: lmwb6, df_shape: (7, 12)
#1310, id: dywc2, df_shape: (105, 12)
#1311, id: dw9ns, df_shape: (66, 12)
#1312, id: uppu4, df_shape: (150, 12)
#1313, id: acb6p, df_shape: (235, 12)
#1314, id: gipix, df_shape: (14, 12)
#1315, id: e61ys, df_shape: (14, 12)
#1316, id: r1a78, df_shape: (23, 12)
#1317, id: aly3t, df_shape: (362, 12)
#1318, id: h0rgf, df_shape: (65, 12)
#1319, id: qprnc, df_shape: (125, 12)
#1320, id: e6jeb, df_shape: (11, 12)
#1321, id: h0oqf, df_shape: (16, 12)
#1322, id: zxdtt, df_shape: (183, 12)
#1323, id: 69lj3, df_shape: (3, 12)
#1324, id: xgxhl, df_shape: (3, 12)
#1325, id: lmeoy, df_shape: (35, 12)
#1326, id: 66aug, df_shape: (26, 12)
#1327, id: hmlsc, df_shape: (223, 12)
#1328, id: g8hj6, df_shape: (21, 12)
#1329, id: d8134, df_shape: (24, 12)
#1330, id: muhz6, df_shape: (7, 12)
#1331, id: v42z1, df_shape: (57, 12)
#1332, id: it0pa, df_shape: (33, 12)
#1333, id: mr22w, df_shape: (139, 12)
#1334, id: zmrbr, df_shape: (30, 12)
#1335, id: cahli, df_shape: (3, 12)
#1336, id: i58pl, df_shape: (11, 12)
#1337, id: cwtx6, df_shape: (14, 12)
#1338, id: krgfs, df_shape: (1998, 12)
#1339, id: uwsb3, df_shape: (10, 12)
#1340, id: pvnom, df_shape: (1425, 12)
#1341, id: iwncl, df_shape: (9, 12)
#1342, id: taqrs, df_shape: (32, 12)
#1343, id: dvbya, df_shape: (27, 12)
#1344, id: 9xfhj, df_shape: (1, 12)
#1345, id: l0809, df_shape: (3, 12)
#1346, id: 38mak, df_shape: (76, 12)
#1347, id: ka3im, df_shape: (21, 12)
#1348, id: xe906, df_shape: (300, 12)

#1349, id: u732n, df_shape: (3, 12)
#1350, id: p1do0, df_shape: (38, 12)
#1351, id: k6i3a, df_shape: (20, 12)
#1352, id: 7bq9e, df_shape: (200, 12)
#1353, id: v68lg, df_shape: (72, 12)
#1354, id: w152e, df_shape: (1207, 12)
#1355, id: tgoxx, df_shape: (36, 12)
#1356, id: 3zuwz, df_shape: (69, 12)
#1357, id: 84qrx, df_shape: (68, 12)
#1358, id: nnjps, df_shape: (80, 12)
#1359, id: w7p1p, df_shape: (18, 12)
#1360, id: bxe6l, df_shape: (22, 12)
#1361, id: hf2j8, df_shape: (260, 12)
#1362, id: jjb9p, df_shape: (48, 12)
#1363, id: 52edr, df_shape: (8, 12)
#1364, id: 31v6g, df_shape: (350, 12)
#1365, id: xddwk, df_shape: (33, 12)
#1366, id: xt2oc, df_shape: (4, 12)
#1367, id: zvdib, df_shape: (83, 12)
#1368, id: aixw7, df_shape: (25, 12)
#1369, id: afrz7, df_shape: (5, 12)
#1370, id: 45f0k, df_shape: (1, 12)
#1371, id: v5m71, df_shape: (10, 12)
#1372, id: bntv4, df_shape: (7, 12)
#1373, id: ln020, df_shape: (830, 12)
#1374, id: vpt9v, df_shape: (2, 12)
#1375, id: umzwq, df_shape: (119, 12)
#1376, id: c0iif, df_shape: (38, 12)
#1377, id: zcosl, df_shape: (13, 12)
#1378, id: 3zpkj, df_shape: (310, 12)
#1379, id: z6j8b, df_shape: (16060, 12)
#1380, id: cqcep, df_shape: (155, 12)
#1381, id: zem2w, df_shape: (16866, 12)
#1382, id: bhock, df_shape: (4419, 12)
#1383, id: z0f8n, df_shape: (226, 12)
#1384, id: h10ni, df_shape: (2576, 12)
#1385, id: 0jp67, df_shape: (72, 12)
#1386, id: zjooo, df_shape: (328, 12)
#1387, id: 49dh6, df_shape: (63, 12)
#1388, id: ius1t, df_shape: (224, 12)
#1389, id: oz6z5, df_shape: (304, 12)
#1390, id: l7bra, df_shape: (319, 12)
#1391, id: kfp1u, df_shape: (153, 12)
#1392, id: cu4rm, df_shape: (65, 12)
#1393, id: nyt1j, df_shape: (87, 12)
#1394, id: nt10f, df_shape: (817, 12)
#1395, id: kfj1m, df_shape: (127, 12)
#1396, id: 3hyvo, df_shape: (59, 12)
#1397, id: dn331, df_shape: (100, 12)
#1398, id: nys0k, df_shape: (355, 12)
#1399, id: lgx6g, df_shape: (366, 12)
#1400, id: txrqh, df_shape: (898, 12)
#1401, id: n7biy, df_shape: (946, 12)
#1402, id: 61yn6, df_shape: (45, 12)
#1403, id: ir0iz, df_shape: (233, 12)
#1404, id: k3qaa, df_shape: (1369, 12)
#1405, id: boegs, df_shape: (4052, 12)
#1406, id: 4frh7, df_shape: (254, 12)
#1407, id: c61je, df_shape: (170, 12)
#1408, id: z3ddl, df_shape: (623, 12)
#1409, id: dd5e2, df_shape: (730, 12)
#1410, id: 09w09, df_shape: (21, 12)
#1411, id: ho895, df_shape: (292, 12)
#1412, id: 42nps, df_shape: (54, 12)
#1413, id: tjdd9, df_shape: (65, 12)
#1414, id: b6c1l, df_shape: (211, 12)
#1415, id: e3uix, df_shape: (201, 12)
#1416, id: t10zq, df_shape: (950, 12)
#1417, id: 03z14, df_shape: (861, 12)
#1418, id: oxacu, df_shape: (47, 12)
#1419, id: 52jw7, df_shape: (90, 12)
#1420, id: 012sd, df_shape: (2, 12)
#1421, id: indmk, df_shape: (90, 12)
#1422, id: mqyna, df_shape: (184, 12)
#1423, id: mrscj, df_shape: (433, 12)
#1424, id: 7mkw3, df_shape: (3516, 12)
#1425, id: qt19y, df_shape: (71, 12)
#1426, id: ey37z, df_shape: (81, 12)
#1427, id: q8pba, df_shape: (187, 12)
#1428, id: gxhm5, df_shape: (191, 12)
#1429, id: jqxiq, df_shape: (183, 12)
#1430, id: g20yl, df_shape: (561, 12)
#1431, id: yaw0l, df_shape: (633, 12)
#1432, id: i90nf, df_shape: (528, 12)
#1433, id: 3p6tq, df_shape: (23, 12)
#1434, id: 74ddc, df_shape: (170, 12)
#1435, id: nap6q, df_shape: (34, 12)
#1436, id: sd9a8, df_shape: (37, 12)
#1437, id: uru84, df_shape: (123, 12)
#1438, id: jpkrh, df_shape: (20, 12)
#1439, id: bil22, df_shape: (642, 12)
#1440, id: cbmff, df_shape: (635, 12)
#1441, id: aeftx, df_shape: (142, 12)
#1442, id: k30mh, df_shape: (449, 12)
#1443, id: logor, df_shape: (388, 12)
#1444, id: k51e0, df_shape: (2254, 12)
#1445, id: hb34k, df_shape: (1574, 12)
#1446, id: 82uit, df_shape: (1153, 12)
#1447, id: r7haq, df_shape: (870, 12)
#1448, id: s45kg, df_shape: (85, 12)
#1449, id: 6ytxo, df_shape: (655, 12)
#1450, id: btpyy, df_shape: (5565, 12)
#1451, id: vghx0, df_shape: (53, 12)
#1452, id: 3hilr, df_shape: (98, 12)
#1453, id: mqfys, df_shape: (78, 12)
#1454, id: idb3a, df_shape: (24, 12)
#1455, id: h69zo, df_shape: (995, 12)
#1456, id: 5wxb2, df_shape: (103, 12)
#1457, id: gkdhe, df_shape: (50, 12)
#1458, id: anf8b, df_shape: (342, 12)
#1459, id: ks4w6, df_shape: (884, 12)
#1460, id: op67k, df_shape: (1363, 12)
#1461, id: todvj, df_shape: (1511, 12)
#1462, id: mq27z, df_shape: (1712, 12)
#1463, id: j955h, df_shape: (1485, 12)
#1464, id: 5cuhe, df_shape: (373, 12)
#1465, id: 5qlmn, df_shape: (556, 12)
#1466, id: pz89f, df_shape: (115, 12)
#1467, id: j5nue, df_shape: (1573, 12)
#1468, id: vsy1m, df_shape: (367, 12)
#1469, id: cw0en, df_shape: (1431, 12)
#1470, id: zp0oa, df_shape: (381, 12)
#1471, id: igupg, df_shape: (1439, 12)
#1472, id: 58wap, df_shape: (383, 12)
#1473, id: 9injl, df_shape: (1472, 12)
#1474, id: 1lkkt, df_shape: (1505, 12)
#1475, id: ibksr, df_shape: (1456, 12)
#1476, id: br3vi, df_shape: (379, 12)
#1477, id: dhc3v, df_shape: (73, 12)
#1478, id: b6850, df_shape: (378, 12)
#1479, id: wsphl, df_shape: (30, 12)
#1480, id: f24yo, df_shape: (342, 12)
#1481, id: 3ex9l, df_shape: (384, 12)
#1482, id: 8vle2, df_shape: (39, 12)
#1483, id: n3ve4, df_shape: (194, 12)
#1484, id: emx2n, df_shape: (29, 12)
#1485, id: psb0m, df_shape: (296, 12)
#1486, id: 7jq73, df_shape: (379, 12)
#1487, id: jwi0o, df_shape: (102, 12)
#1488, id: 4tuo8, df_shape: (4967, 12)
#1489, id: v8h1m, df_shape: (304, 12)
#1490, id: df5zs, df_shape: (852, 12)
#1491, id: 62gvh, df_shape: (265, 12)
#1492, id: 5vgy3, df_shape: (43, 12)
#1493, id: hmoo8, df_shape: (73, 12)
#1494, id: 7a5dz, df_shape: (1445, 12)
#1495, id: 4shlw, df_shape: (191, 12)
#1496, id: 1khil, df_shape: (295, 12)
#1497, id: vuj0o, df_shape: (295, 12)
#1498, id: c7x1u, df_shape: (38, 12)
#1499, id: 0zxny, df_shape: (126, 12)
#1500, id: h8m72, df_shape: (251, 12)
#1501, id: i151o, df_shape: (48, 12)
#1502, id: uv3hk, df_shape: (711, 12)
#1503, id: snzel, df_shape: (316, 12)
#1504, id: 6ozff, df_shape: (381, 12)
#1505, id: wa7mb, df_shape: (184, 12)
#1506, id: 8stoy, df_shape: (1068, 12)
#1507, id: yxmqu, df_shape: (1068, 12)
#1508, id: imkmt, df_shape: (1063, 12)
#1509, id: 6r4w5, df_shape: (1061, 12)
#1510, id: nhzvy, df_shape: (998, 12)
#1511, id: 7gsyp, df_shape: (1088, 12)
#1512, id: fnq8x, df_shape: (1072, 12)
#1513, id: 5k5fg, df_shape: (1090, 12)
#1514, id: bgm6i, df_shape: (1196, 12)
#1515, id: u9ny2, df_shape: (1043, 12)
#1516, id: w2sy2, df_shape: (229, 12)
#1517, id: f3vhk, df_shape: (1071, 12)
#1518, id: 60cz6, df_shape: (219, 12)
#1519, id: no273, df_shape: (4782, 12)
#1520, id: lwo72, df_shape: (1877, 12)
#1521, id: i9qc6, df_shape: (26, 12)
#1522, id: rpjz4, df_shape: (2002, 12)
#1523, id: zamrp, df_shape: (272, 12)
#1524, id: t962v, df_shape: (278, 12)
#1525, id: pbtv0, df_shape: (395, 12)
#1526, id: 1o4gw, df_shape: (53, 12)
#1527, id: b65mw, df_shape: (38, 12)
#1528, id: 4pnrc, df_shape: (69, 12)
#1529, id: erklu, df_shape: (636, 12)
#1530, id: 31mto, df_shape: (378, 12)
#1531, id: opbt4, df_shape: (1003, 12)
#1532, id: cle7u, df_shape: (208, 12)
#1533, id: ih5do, df_shape: (565, 12)
#1534, id: m6rrm, df_shape: (523, 12)
#1535, id: epu7d, df_shape: (144, 12)
#1536, id: w3jku, df_shape: (91, 12)
#1537, id: 9ne77, df_shape: (29, 12)
#1538, id: ikerx, df_shape: (141, 12)
#1539, id: jmgty, df_shape: (140, 12)
#1540, id: smctd, df_shape: (77, 12)
#1541, id: 39k64, df_shape: (124, 12)
#1542, id: gms0v, df_shape: (287, 12)
#1543, id: w1nt7, df_shape: (62, 12)
#1544, id: easop, df_shape: (2, 12)
#1545, id: cxcqe, df_shape: (51, 12)
#1546, id: g2q0v, df_shape: (19, 12)
#1547, id: td9z7, df_shape: (13, 12)
#1548, id: dz85z, df_shape: (319, 12)
#1549, id: j7h3v, df_shape: (30, 12)
#1550, id: z2hj2, df_shape: (239, 12)
#1551, id: e6bxr, df_shape: (17, 12)
#1552, id: 2u5jc, df_shape: (128, 12)
#1553, id: 3g8su, df_shape: (1005, 12)
#1554, id: a7821, df_shape: (1278, 12)
#1555, id: nj6lq, df_shape: (1134, 12)
#1556, id: qqafh, df_shape: (82, 12)
#1557, id: orh0j, df_shape: (96, 12)
#1558, id: nem11, df_shape: (61, 12)
#1559, id: x2j9z, df_shape: (9, 12)
#1560, id: ouyt4, df_shape: (1125, 12)
#1561, id: hvsuj, df_shape: (116, 12)
#1562, id: 7l830, df_shape: (400, 12)
#1563, id: mmixo, df_shape: (24, 12)
#1564, id: 3t1ld, df_shape: (617, 12)
#1565, id: kbce1, df_shape: (555, 12)
#1566, id: li3tt, df_shape: (214, 12)
#1567, id: zgatk, df_shape: (14, 12)
#1568, id: le9uc, df_shape: (379, 12)
#1569, id: 1y2tm, df_shape: (21, 12)
#1570, id: ygeqt, df_shape: (47, 12)
#1571, id: scve8, df_shape: (380, 12)
#1572, id: rzsxf, df_shape: (378, 12)
#1573, id: slzx5, df_shape: (339, 12)
#1574, id: 4e2rt, df_shape: (24, 12)
#1575, id: t8ud5, df_shape: (263, 12)
#1576, id: kyx8d, df_shape: (1004, 12)
#1577, id: mwto5, df_shape: (253, 12)
#1578, id: 2jmy1, df_shape: (109, 12)
#1579, id: gssnu, df_shape: (9, 12)
#1580, id: 6f5ef, df_shape: (369, 12)
#1581, id: q5z78, df_shape: (356, 12)
#1582, id: ik7fo, df_shape: (60, 12)
#1583, id: 6xv6h, df_shape: (376, 12)
#1584, id: mk64z, df_shape: (100, 12)
#1585, id: 79kph, df_shape: (426, 12)
#1586, id: wsgj1, df_shape: (75, 12)
#1587, id: xmhbr, df_shape: (81, 12)
#1588, id: 0yz7q, df_shape: (37, 12)
#1589, id: xlsqr, df_shape: (13, 12)
#1590, id: mjto4, df_shape: (883, 12)
#1591, id: ojvxr, df_shape: (359, 12)

KeyboardInterrupt:

In [ ]:
len(auction_dictinoary)

## get single auction to test with

In [ ]:
df = auction_dictinoary['jefix'].copy(deep=True)

# add temporal difference between bids
df['date_time'] = pd.to_datetime(df['time'])

# must sort by date_time, index and time do not have same order
df = df.sort_values(['date_time']) 

tdelta = df['date_time'].diff()
tdelta.fillna(0 , inplace=True)
df['time_delta_auction_bids'] = pd.to_timedelta(tdelta) / np.timedelta64(1, 's')

df = df.reset_index()

In [ ]:
df[1:]['time_delta_auction_bids'].describe()

In [ ]:
# get describe series (not including first row delta will always be 0)
describe_of_time_delta_auction_bids = df[1:]['time_delta_auction_bids'].describe()

# get axes labels for label describe
describe_axes = describe_of_time_delta_auction_bids.axes[0]
describe_axes

# add distrubtion of deltas data
for i in range(1, len(describe_axes)):
    df['{}_{}'.format('time_delta_auction_bids', describe_axes[i])] = describe_of_time_delta_auction_bids[i]
    
df['time_delta_bids_in_auction_median'] = df[1:]['time_delta_auction_bids'].median()
df['time_delta_bids_in_auction_kurtosis'] = df[1:]['time_delta_auction_bids'].kurtosis()
df['total_bids_in_auction'] = df.shape[0] # total bid count

df['first_auction_bid'] = 0
df['last_auction_bid'] = 0
df.iloc[0, df.columns.get_loc('first_auction_bid')] = 1
df.iloc[df.shape[0] - 1, df.columns.get_loc('last_auction_bid')] = 1

In [ ]:
df.head(3)

In [ ]:
list_of_df = []


for auction in auction_dictinoary:
    
    df = auction_dictinoary[auction]
    
    # add temporal difference between bids
    df['date_time'] = pd.to_datetime(df['time'])

    # must sort by date_time, index and time do not have same order
    df = df.sort_values(['date_time']) 

    tdelta = df['date_time'].diff()
    tdelta.fillna(0 , inplace=True)
    df['time_delta_auction_bids'] = pd.to_timedelta(tdelta) / np.timedelta64(1, 's')

    df = df.reset_index()
    
    # get describe series (not including first row delta will always be 0)
    describe_of_time_delta_auction_bids = df[1:]['time_delta_auction_bids'].describe()

    # get axes labels for label describe
    describe_axes = describe_of_time_delta_auction_bids.axes[0]

    # add distrubtion of deltas data
    for i in range(1, len(describe_axes)):
        df['{}_{}'.format('time_delta_auction_bids', describe_axes[i])] = describe_of_time_delta_auction_bids[i]

    df['time_delta_bids_in_auction_median'] = df[1:]['time_delta_auction_bids'].median()
    df['time_delta_bids_in_auction_kurtosis'] = df[1:]['time_delta_auction_bids'].kurtosis()
    df['total_bids_in_auction'] = df.shape[0] # total bid count
    
    # add column to show if this was first and last bid in auction
    df['first_auction_bid'] = 0
    df['last_auction_bid'] = 0
    df.iloc[0, df.columns.get_loc('first_auction_bid')] = 1
    df.iloc[df.shape[0] - 1, df.columns.get_loc('last_auction_bid')] = 1
    
    list_of_df.append(df)


unordered_df = pd.concat(list_of_df, ignore_index=True)

In [ ]:
# (3071224, 27) shape of training
# (4585110, 26) shape of testing
unordered_df.shape

In [ ]:
unordered_df.head(10)

In [ ]:
df_ordered = unordered_df.sort_values(by='index')
df_ordered.head(10)

In [234]:
# df_ordered.to_csv('dataset/auction_data_added_testing.csv', index=None)
df_ordered.to_csv('dataset/auction_data_added_training.csv', index=None)

In [235]:
# df = pd.read_csv('dataset/auction_data_added_testing.csv')
df = pd.read_csv('dataset/auction_data_added_training.csv')
df.head(10)

,index,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url,payment_account,address,date_time,time_delta_auction_bids,time_delta_auction_bids_mean,time_delta_auction_bids_std,time_delta_auction_bids_min,time_delta_auction_bids_25%,time_delta_auction_bids_50%,time_delta_auction_bids_75%,time_delta_auction_bids_max,time_delta_bids_in_auction_median,time_delta_bids_in_auction_kurtosis,total_bids_in_auction,first_auction_bid,last_auction_bid
0,0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:03.157894736,0.000000,6.594607,10.631530,0.000000,0.631579,2.473684,8.052632,111.105263,2.473684,19.243910,2068,1,0
1,1,14,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,wberf,jewelry,phone15,9759243263157894,au,134.243.148.253,vasstdc27m7nks3,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:03.263157894,0.000000,4263.473684,4448.048902,1249.210526,1709.157895,2169.105263,5770.605263,9372.105263,2169.105263,NaN,4,1,0
2,2,106,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,hw5at,jewelry,phone80,9759243736842105,ke,227.231.81.211,v2gyrh0dbr31atn,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:03.736842105,0.000000,48.986369,145.055987,0.052632,7.223684,19.105263,41.565789,2080.315789,19.105263,143.252999,279,1,0
3,3,152,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,uw3sx,jewelry,phone41,9759243947368421,iq,140.231.164.76,xdsfv4oevw5owkq,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:03.947368421,0.000000,9.655037,12.437212,0.000000,2.052632,5.526316,12.736842,121.842105,5.526316,18.918137,1410,1,0
4,4,155,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,q79ya,jewelry,phone102,9759244000000000,za,187.81.242.103,eex5it5avrad6s8,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:04.000000000,0.000000,15.387376,35.667397,0.000000,2.052632,6.473684,16.236842,477.368421,6.473684,98.942022,548,1,0
5,5,169,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,qcppg,jewelry,phone5,9759244052631578,in,13.136.161.106,vasstdc27m7nks3,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:04.052631578,0.000000,6.651990,14.990715,0.000000,0.947368,2.473684,6.684211,375.578947,2.473684,200.810588,2051,1,0
6,6,224,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,fqfbw,jewelry,phone4,9759244368421052,in,153.47.226.142,vasstdc27m7nks3,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:04.368421052,0.000000,29.921745,44.757204,0.157895,5.815789,15.605263,35.842105,402.157895,15.605263,23.583485,305,1,0
7,7,366,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,idfc3,jewelry,phone4,9759245052631578,ke,207.97.126.108,vasstdc27m7nks3,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:05.052631578,0.000000,14.482801,32.580940,0.000000,2.526316,6.210526,14.789474,590.526316,6.210526,136.969767,942,1,0
8,8,421,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759245368421052,us,69.166.231.58,vasstdc27m7nks3,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:05.368421052,1.894737,6.594607,10.631530,0.000000,0.631579,2.473684,8.052632,111.105263,2.473684,19.243910,2068,0,0
9,9,422,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,2yowp,jewelry,phone46,9759245368421052,iq,140.231.164.76,hsfvg8lforbluvq,a3d2de7675556553a5f08e4c88d2c2282ay1v,7f4c6ac489cbd95e38e4f093bb308af5jae25,1970-04-23 22:54:05.368421052,0.000000,4.715950,6.187722,0.000000,1.052632,2.736842,6.000000,70.684211,2.736842,22.017629,2893,1,0